-- OPF - CARD TO CARD -- aumentamos el group control para 20% por tener un aumento en la tabla

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20251110_GUBELARMINO` AS
    SELECT 
      *except(MAX_DEUDA_INGRESO, BT_VU_PRESUMED_INCOME__OPF_MAX_LIMIT_TC_AMT,FLAG_CONTROL_GROUP),
      CASE 
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('A') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) <  '8'  THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('A') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '8' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('B') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) <  '8'  THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('B') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '8' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('C') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) <  '8'  THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('C') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '8' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('D') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) <  '8'  THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('D') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '8' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('E') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) <  '8'  THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('E') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '8' THEN true
      ELSE null
      END AS FLAG_CONTROL_GROUP,
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_CARD_TO_CARD_MLB` 
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_20251110_GUBELARMINO` AS
    SELECT 
      A.*EXCEPT(CAMPAIGN_CONTROL_GROUP),
      B.FLAG_CONTROL_GROUP AS CAMPAIGN_CONTROL_GROUP 
      FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` A
    LEFT JOIN `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20251110_GUBELARMINO` B
    ON user_id = cus_cust_id
    where A.FRIDAY_SEGMENT = 'CARD_TO_CARD'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

-- PISOS MINIMOS
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_20251110_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where FRIDAY_SEGMENT = 'PISOS_MINIMOS'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20251110_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_PISOS_MINIMOS_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

-- REACTIVACION: En 202511 impactamos solo 60% da base, mantenendo 20% dese como control por tener un stock muy grande

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_ANALITICA_20251110_GUBELARMINO` AS
    SELECT 
      *except(MAX_DEUDA_INGRESO, FLAG_CONTROL_GROUP), 
      CASE 
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('A') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '4' THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('A') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '6' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('A') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '6' THEN null
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('B') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '4' THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('B') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '6' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('B') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '6' THEN null
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('C') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '4' THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('C') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '6' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('C') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '6' THEN null
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('D') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '4' THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('D') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '6' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('D') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '6' THEN null
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('E') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '4' THEN false
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('E') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) < '6' THEN true
        WHEN INTERNAL_RATING_BEHAVIOR_TC IN ('E') AND RIGHT(cast(CUS_CUST_ID as STRING), 1) >= '6' THEN null
      ELSE null
      END AS FLAG_CONTROL_GROUP,
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_REACTIVATION_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
      and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_20251110_GUBELARMINO` AS
    SELECT 
      A.*EXCEPT(CAMPAIGN_CONTROL_GROUP),
      B.FLAG_CONTROL_GROUP AS CAMPAIGN_CONTROL_GROUP
    FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` A
    LEFT JOIN `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_ANALITICA_20251110_GUBELARMINO` B
    on cus_cust_id = user_id
    where A.FRIDAY_SEGMENT = 'REACTIVATION'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and B.FLAG_CONTROL_GROUP is not null
    and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;
-- ADECUACION_RENTA
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_ADECUACION_RENTA_20251110_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where FRIDAY_SEGMENT = 'ADECUACION_RENTA'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_ADECUACION_RENTA_ANALITICA_20251110_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_ADECUACION_RENTA_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

-- JOURNEY_LIMITE
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_20251110_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where FRIDAY_SEGMENT = 'JOURNEY_LIMITE'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_ANALITICA_20251110_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_JOURNEY_LIMITE_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251106_GI_GC_GUBELARMINO`)
    and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;


--- EVALUACION ---

SELECT
  -- *
  POLITICA,
  FLAG_CONTROL_GROUP,
  case
    when nise = 'BRONZE' then 'a.bronze'
    when nise = 'SILVER' then 'b.silver'
    when nise = 'GOLD' then 'c.gold'
    when nise = 'PLATINUM' then 'd.platinum'
  end as nise_ordenado,
  count(1) as cant,
  ROUND(SUM(WANDA__CURRENT_LIMIT_CCARD),2) as limite_actual,
  ROUND(SUM(GENERAL_LIMIT),2) as limite_final,
  ROUND(SUM(GENERAL_LIMIT-WANDA__CURRENT_LIMIT_CCARD),2) as exposicion_adicional
FROM (

  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'CARD_TO_CARD' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20251110_GUBELARMINO`
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'PISOS_MINIMOS' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20251110_GUBELARMINO`
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'REACTIVACION' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_ANALITICA_20251110_GUBELARMINO` where FLAG_CONTROL_GROUP is not null
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'ADECUACION_RENTA' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_ADECUACION_RENTA_ANALITICA_20251110_GUBELARMINO` 
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'JOURNEY_LIMITE' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_ANALITICA_20251110_GUBELARMINO` 
)
group by all
order by 1