###### INSERT BAU #######

#### insert 1

-- `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 

--- IMPACTO

CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'BAU', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'GESTION' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---2676a104-8170-46cc-ac6a-e7e05549c0f8

--CONTROL
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'BAU', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'CONTROL' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
--d4466857-585e-411b-8c15-9209f39100be

--- INSERT EN CEREBRO 
      
--insert GI 1

INSERT INTO `meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL`
(
  USER_ID,
  GENERAL_LIMIT,
  WITHDRAW_LIMIT,
  SITE_ID,
  PRIORITY,
  IS_UPSELL,
  CAMPAIGN_ID,
  AUD_INS_USER
)
select  
  cus_cust_id as USER_ID,
  CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
  50 as WITHDRAW_LIMIT,
  'MLB' SITE_ID,
  0 PRIORITY,
  1 IS_UPSELL,
  '2676a104-8170-46cc-ac6a-e7e05549c0f8' CAMPAIGN_ID,
  'gubelarmino' AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 
where grupos like '%GI%' and upsell = 'bau'
;



---insert GC

INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)  
select
  cus_cust_id as USER_ID,
  CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
  50 as WITHDRAW_LIMIT,
  'MLB' SITE_ID,
  0 PRIORITY,
  1 IS_UPSELL,
  'd4466857-585e-411b-8c15-9209f39100be' CAMPAIGN_ID,
  CASE WHEN grupos = 'GC' THEN TRUE ELSE FALSE END AS CAMPAIGN_CONTROL_GROUP,
 'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 
where grupos like '%GC%' and upsell = 'bau'
;

---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'd4466857-585e-411b-8c15-9209f39100be' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime '2025-09-09 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`  a
where grupos like '%GC%' and upsell = 'bau') A
;


--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'2676a104-8170-46cc-ac6a-e7e05549c0f8' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime '2025-09-09 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`  a
where grupos like '%GI%' and upsell = 'bau') A
;


###### INSERT VIPS MP #######

#### insert 1

-- `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 

-- IMPACTO
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'VIPs MP', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'GESTION' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---ceefa133-220a-4bfe-b7f7-6cc4b24082f1

--CONTROL
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'VIPs MP', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'CONTROL' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---24b43614-ef14-484b-963c-8edeb0abe28f


--- INSERT EN CEREBRO 
      
--insert GI 1

INSERT INTO `meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL`(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
AUD_INS_USER)
select  
cus_cust_id as USER_ID,
CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
50 as WITHDRAW_LIMIT,
'MLB' SITE_ID,
0 PRIORITY,
1 IS_UPSELL,
'ceefa133-220a-4bfe-b7f7-6cc4b24082f1' CAMPAIGN_ID,
'gubelarmino' AUD_INS_USER
from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 
where grupos like '%GI%' and upsell = 'vips mp'
;



---insert GC

INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)  
select
cus_cust_id as USER_ID,
CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
50 as WITHDRAW_LIMIT,
'MLB' SITE_ID,
0 PRIORITY,
1 IS_UPSELL,
'24b43614-ef14-484b-963c-8edeb0abe28f' CAMPAIGN_ID,
CASE WHEN grupos = 'GC' THEN TRUE ELSE FALSE END AS CAMPAIGN_CONTROL_GROUP,
 'gubelarmino' AS AUD_INS_USER
from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 
where grupos like '%GC%' and upsell = 'vips mp'
;




---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'24b43614-ef14-484b-963c-8edeb0abe28f' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime '2025-09-09 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`  a
where grupos like '%GC%' and upsell = 'vips mp') A
;


--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'ceefa133-220a-4bfe-b7f7-6cc4b24082f1' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime '2025-09-09 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`  a
where grupos like '%GI%' and upsell = 'vips mp') A
;


###### INSERT VIPS MKPLACE #######

#### insert 1

-- `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 

-- IMPACTO
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'CROSS', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'VIPs ML', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'GESTION' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---719d6fda-216d-45a0-a3e3-3a226171047b

--CONTROL
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'CROSS', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'VIPs ML', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'CONTROL' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---1dc4010a-06f7-4874-82c6-50ab432589ba


--- INSERT EN CEREBRO 
      
--insert GI 1

INSERT INTO `meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL`(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
AUD_INS_USER)
select  
cus_cust_id as USER_ID,
CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
50 as WITHDRAW_LIMIT,
'MLB' SITE_ID,
0 PRIORITY,
1 IS_UPSELL,
'719d6fda-216d-45a0-a3e3-3a226171047b' CAMPAIGN_ID,
'gubelarmino' AUD_INS_USER
from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 
where grupos like '%GI%' and upsell = 'vips mktplace'
;



---insert GC

INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)  
select
cus_cust_id as USER_ID,
CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
50 as WITHDRAW_LIMIT,
'MLB' SITE_ID,
0 PRIORITY,
1 IS_UPSELL,
'1dc4010a-06f7-4874-82c6-50ab432589ba' CAMPAIGN_ID,
CASE WHEN grupos = 'GC' THEN TRUE ELSE FALSE END AS CAMPAIGN_CONTROL_GROUP,
 'gubelarmino' AS AUD_INS_USER
from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO` 
where grupos like '%GC%' and upsell = 'vips mktplace'
;




---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'1dc4010a-06f7-4874-82c6-50ab432589ba' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime '2025-09-09 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`  a
where grupos like '%GC%' and upsell = 'vips mktplace') A
;


--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'719d6fda-216d-45a0-a3e3-3a226171047b' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime '2025-09-09 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`  a
where grupos like '%GI%' and upsell = 'vips mktplace') A
;
