
-- OPF - CARD TO CARD

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_20250912_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where FRIDAY_SEGMENT = 'CARD_TO_CARD'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20250912_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO, BT_VU_PRESUMED_INCOME__OPF_MAX_LIMIT_TC_AMT), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_CARD_TO_CARD_MLB` 
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`)
;

-- PISOS MINIMOS
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_20250912_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where FRIDAY_SEGMENT = 'PISOS_MINIMOS'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20250912_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_PISOS_MINIMOS_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`)
;

-- REACTIVACION
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_20250912_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where FRIDAY_SEGMENT = 'REACTIVATION'
    and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_ANALITICA_20250912_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_REACTIVATION_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20250908_GI_GC_GUBELARMINO`)
;


/*
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------- OPEN FINANCE ----------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*/

CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'CROSS', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'OPF', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'' --10 Campaign_group_desc
);

CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'CROSS', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'OPF', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'' --10 Campaign_group_desc
);

-- check
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` 
where sit_site_id = 'MLB'AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;

-- GESTION: 7eb08e36-21e3-4eab-9c99-5b904119c55e
-- CONTROL: 79a68d51-53d2-4e6c-bbd5-0095badead33


-- GESTION
INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL (
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)
select
    USER_ID,
    GENERAL_LIMIT,
    50 as WITHDRAW_LIMIT,
    SITE_ID,
    0 PRIORITY,
    IS_UPSELL,
    '7eb08e36-21e3-4eab-9c99-5b904119c55e' AS CAMPAIGN_ID,
    CAMPAIGN_CONTROL_GROUP,
    'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_20250912_GUBELARMINO` 
WHERE CAMPAIGN_CONTROL_GROUP = false
-- Esta declaración agregó 20,871 filas a EOC_TC_C_UPSELL_DOWNSELL.
;

-- CONTROL
INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL (
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)
select
    USER_ID,
    GENERAL_LIMIT,
    50 as WITHDRAW_LIMIT,
    SITE_ID,
    0 PRIORITY,
    IS_UPSELL,
    '79a68d51-53d2-4e6c-bbd5-0095badead33' AS CAMPAIGN_ID,
    CAMPAIGN_CONTROL_GROUP,
    'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_20250912_GUBELARMINO` 
WHERE CAMPAIGN_CONTROL_GROUP = true
-- Esta declaración agregó 1,090 filas a EOC_TC_C_UPSELL_DOWNSELL.
;


/*
INSERT NA BASE DE CAMPANHA
*/

-- CAMPAIGN

-- GESTION

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'7eb08e36-21e3-4eab-9c99-5b904119c55e' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
GENERAL_LIMIT as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
INTERNAL_RATING_BEHAVIOR_TC AS RATING_BHV_TC,
INTERNAL_RATING_UPSELL_TC AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20250912_GUBELARMINO` a -- mudar
where FLAG_CONTROL_GROUP is false) A
;
-- Esta declaración agregó 20,871 filas a RBA_TC_CAMPAIGN_CARTERA.

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'79a68d51-53d2-4e6c-bbd5-0095badead33' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
GENERAL_LIMIT as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
INTERNAL_RATING_BEHAVIOR_TC AS RATING_BHV_TC,
INTERNAL_RATING_UPSELL_TC AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20250912_GUBELARMINO` a -- mudar
where FLAG_CONTROL_GROUP is true) A
;
-- Esta declaración agregó 1,090 filas a RBA_TC_CAMPAIGN_CARTERA.

/*
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------- PISOS MINIMOS ----------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*/

CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'PISOS MIN', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'' --10 Campaign_group_desc
);

CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'PISOS MIN', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'' --10 Campaign_group_desc
);

-- check
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` 
where sit_site_id = 'MLB'AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;

-- GESTION: cf444b23-4413-4e46-8278-7e32d2169d21
-- CONTROL: 1d1440e2-064c-4320-b2b2-93e7cd369098


-- GESTION
INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL (
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)
select
    USER_ID,
    GENERAL_LIMIT,
    50 as WITHDRAW_LIMIT,
    SITE_ID,
    0 PRIORITY,
    IS_UPSELL,
    'cf444b23-4413-4e46-8278-7e32d2169d21' AS CAMPAIGN_ID,
    CAMPAIGN_CONTROL_GROUP,
    'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_20250912_GUBELARMINO` 
WHERE CAMPAIGN_CONTROL_GROUP = false
and user_id not in (  SELECT cus_cust_id FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_47172e4e-e7db-4029-b917-123458e8aa19-1` where `cluster` > 0 and exception = false and eliminated_by_rk = false)
-- Esta declaración agregó 116,104 filas a EOC_TC_C_UPSELL_DOWNSELL.
;

-- CONTROL
INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL (
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)
select
    USER_ID,
    GENERAL_LIMIT,
    50 as WITHDRAW_LIMIT,
    SITE_ID,
    0 PRIORITY,
    IS_UPSELL,
    '1d1440e2-064c-4320-b2b2-93e7cd369098' AS CAMPAIGN_ID,
    CAMPAIGN_CONTROL_GROUP,
    'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_20250912_GUBELARMINO` 
WHERE CAMPAIGN_CONTROL_GROUP = true
and user_id not in (  SELECT cus_cust_id FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_47172e4e-e7db-4029-b917-123458e8aa19-1` where `cluster` > 0 and exception = false and eliminated_by_rk = false)
-- Esta declaración agregó 6,100 filas a EOC_TC_C_UPSELL_DOWNSELL.
;


/*
INSERT NA BASE DE CAMPANHA
*/

-- CAMPAIGN

-- GESTION

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'cf444b23-4413-4e46-8278-7e32d2169d21' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
GENERAL_LIMIT as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
INTERNAL_RATING_BEHAVIOR_TC AS RATING_BHV_TC,
INTERNAL_RATING_UPSELL_TC AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20250912_GUBELARMINO` a -- mudar
where FLAG_CONTROL_GROUP is false
and cus_cust_id not in (  SELECT cus_cust_id FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_47172e4e-e7db-4029-b917-123458e8aa19-1` where `cluster` > 0 and exception = false and eliminated_by_rk = false)
) A
;
-- Esta declaración agregó 116,104 filas a RBA_TC_CAMPAIGN_CARTERA.

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'1d1440e2-064c-4320-b2b2-93e7cd369098' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
GENERAL_LIMIT as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
INTERNAL_RATING_BEHAVIOR_TC AS RATING_BHV_TC,
INTERNAL_RATING_UPSELL_TC AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20250912_GUBELARMINO` a -- mudar
where FLAG_CONTROL_GROUP is true
and cus_cust_id not in (  SELECT cus_cust_id FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_47172e4e-e7db-4029-b917-123458e8aa19-1` where `cluster` > 0 and exception = false and eliminated_by_rk = false)
) A
;
-- Esta declaración agregó 6,100 filas a RBA_TC_CAMPAIGN_CARTERA.