-- OPF - CARD TO CARD

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20251212_GUBELARMINO` AS
    SELECT 
      *except(MAX_DEUDA_INGRESO),
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_CARD_TO_CARD_MLB` 
    where 1=1
      and cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_20251212_GUBELARMINO` AS
    SELECT 
      *,
      FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB`
    where 1=1
      and FRIDAY_SEGMENT = 'CARD_TO_CARD'
      and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

-- PISOS MINIMOS
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20251212_GUBELARMINO` AS
    SELECT *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_PISOS_MINIMOS_MLB`
    where cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
    and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_20251212_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where 1=1
      and FRIDAY_SEGMENT = 'PISOS_MINIMOS'
      and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

-- REACTIVACION
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_20251212_GUBELARMINO` AS
    SELECT 
      *,
    FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB`
    where 1=1
      and FRIDAY_SEGMENT = 'REACTIVATION'
      and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_ANALITICA_20251212_GUBELARMINO` AS
    SELECT 
      *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_REACTIVATION_MLB`
    where 1=1
      and cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;


-- ADECUACION_RENTA
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_ADECUACION_RENTA_20251212_GUBELARMINO` AS
    SELECT * FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where 1=1
      and FRIDAY_SEGMENT = 'ADECUACION_RENTA'
      and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_ADECUACION_RENTA_ANALITICA_20251212_GUBELARMINO` AS
    SELECT 
      *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_ADECUACION_RENTA_MLB`
    where 1=1
      and cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

-- JOURNEY_LIMITE
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_20251212_GUBELARMINO` AS
    SELECT 
      * 
    FROM `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_MLB` 
    where 1=1
      and FRIDAY_SEGMENT = 'JOURNEY_LIMITE'
      and user_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and user_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_ANALITICA_20251212_GUBELARMINO` AS
    SELECT 
      *except(MAX_DEUDA_INGRESO), 
    from `meli-bi-data.SBOX_IT_CREDITS_CREDITSTBL.FRIDAY_CCARD_UPSELL_JOURNEY_LIMITE_MLB`
    where 1=1
      and cus_cust_id not in (select cus_cust_id from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO`)
      and cus_cust_id not in (select cus_cust_id from `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`)
;


--- EVALUACION ---

SELECT
  -- *
  POLITICA,
  FLAG_CONTROL_GROUP,
  case
    when nise = 'BRONZE' then 'a.bronze'
    when nise = 'SILVER' then 'b.silver'
    when nise = 'GOLD' then 'c.gold'
    when nise = 'PLATINUM' then 'd.platinum'
  end as nise_ordenado,
  count(1) as cant,
  ROUND(SUM(WANDA__CURRENT_LIMIT_CCARD),2) as limite_actual,
  ROUND(SUM(GENERAL_LIMIT),2) as limite_final,
  ROUND(SUM(GENERAL_LIMIT-WANDA__CURRENT_LIMIT_CCARD),2) as exposicion_adicional
FROM (

  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'CARD_TO_CARD' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_CARD_TO_CARD_ANALITICA_20251212_GUBELARMINO`
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'PISOS_MINIMOS' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_PISOS_MINIMOS_ANALITICA_20251212_GUBELARMINO`
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'REACTIVACION' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_REACTIVATION_ANALITICA_20251212_GUBELARMINO` where FLAG_CONTROL_GROUP is not null
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'ADECUACION_RENTA' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_ADECUACION_RENTA_ANALITICA_20251212_GUBELARMINO` 
  union all
  select cus_cust_id, WANDA__CURRENT_LIMIT_CCARD, GENERAL_LIMIT, nise, FLAG_CONTROL_GROUP, 'JOURNEY_LIMITE' AS POLITICA from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_ANALITICA_20251212_GUBELARMINO` 
)
group by all
order by 1