-- BAU
-- SELECT * FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_f9cf454f-f120-4e36-b5cc-d7dc7bbbd9e9-1`;SELECT POL.*, RK.eliminated_by_rk FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_f9cf454f-f120-4e36-b5cc-d7dc7bbbd9e9-1` AS POL INNER JOIN `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_f9cf454f-f120-4e36-b5cc-d7dc7bbbd9e9-1` AS RK ON POL.CUS_CUST_ID = RK.CUS_CUST_ID;SELECT * FROM `meli-bi-data.SBOX_CREDITSSIGMA.EOC_CAMPAIGN_EXECUTION_DETAIL` WHERE EXECUTION_ID = 'f9cf454f-f120-4e36-b5cc-d7dc7bbbd9e9';

-- VIP MP
-- SELECT * FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_7f548ce6-9983-4705-8397-a2d558f55a6f-1`;SELECT POL.*, RK.eliminated_by_rk FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_7f548ce6-9983-4705-8397-a2d558f55a6f-1` AS POL INNER JOIN `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_7f548ce6-9983-4705-8397-a2d558f55a6f-1` AS RK ON POL.CUS_CUST_ID = RK.CUS_CUST_ID;SELECT * FROM `meli-bi-data.SBOX_CREDITSSIGMA.EOC_CAMPAIGN_EXECUTION_DETAIL` WHERE EXECUTION_ID = '7f548ce6-9983-4705-8397-a2d558f55a6f';

-- VIP MKP
-- SELECT * FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_9b5f8a28-031a-4cbd-86ec-42f305b99e2b-1`;SELECT POL.*, RK.eliminated_by_rk FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_9b5f8a28-031a-4cbd-86ec-42f305b99e2b-1` AS POL INNER JOIN `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_9b5f8a28-031a-4cbd-86ec-42f305b99e2b-1` AS RK ON POL.CUS_CUST_ID = RK.CUS_CUST_ID;SELECT * FROM `meli-bi-data.SBOX_CREDITSSIGMA.EOC_CAMPAIGN_EXECUTION_DETAIL` WHERE EXECUTION_ID = '9b5f8a28-031a-4cbd-86ec-42f305b99e2b';

CREATE OR REPLACE TEMP TABLE TMP_KILLERS AS 
    SELECT
        *
    FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_f9cf454f-f120-4e36-b5cc-d7dc7bbbd9e9-1`
;

CREATE OR REPLACE TEMP TABLE TMP_POLITICA_MP AS 
    SELECT
        *
    FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_7f548ce6-9983-4705-8397-a2d558f55a6f-1`
;

CREATE OR REPLACE TEMP TABLE TMP_POLITICA_MKTPLACE AS 
    SELECT 
        CUS_CUST_ID, 
        MULTIP_NOM_UPS,
        LIMITE_MULTIPLICADOR,
        `CLUSTER`, 
        PAGO_MIN_TC_TEORICO, 
        NIVEL_USO_TC_TEORICO, 
        PAGO_MIN_TC_UPS, 
        NIVEL_USO_TC_UPS 
    FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_9b5f8a28-031a-4cbd-86ec-42f305b99e2b-1`
;

CREATE OR REPLACE TEMP TABLE TMP_POLITICA_BAU AS
    SELECT 
        CUS_CUST_ID, 
        MULTIP_NOM_UPS,
        LIMITE_MULTIPLICADOR,
        `CLUSTER`, 
        PAGO_MIN_TC_TEORICO, 
        NIVEL_USO_TC_TEORICO, 
        PAGO_MIN_TC_UPS, 
        NIVEL_USO_TC_UPS, 
        RCI_CONJUNTA, 
        WANDA__TEORIC_RCI_VAL 
    FROM `meli-bi-data.SBOX_CREDITSSIGMA.CAMP_EOC_RK_POLICY_f9cf454f-f120-4e36-b5cc-d7dc7bbbd9e9-1`

;

CREATE OR REPLACE TEMP TABLE TMP_TABLA_CC AS 

  select
    cus_cust_id,
    case
      when score_bhv_neg_mxp.RATING_BHV_MXP_NEG is not null then score_bhv_neg_mxp.RATING_BHV_MXP_NEG
      when score_bhv_no_neg_mxp.RATING_BHV_MXP_NO_NEG is not null then  score_bhv_no_neg_mxp.RATING_BHV_MXP_NO_NEG
      else 'Sin Rating bhv'
    end as NUEVO_RATING_MXP_PARA_PRICING,
  from 
  (
    select 
      distinct CUS_CUST_ID
      ,SCORE_DT
      ,CRD_MODEL
      ,crd_version
      ,INTERNAL_RATING_TAG AS RATING_BHV_MXP_NEG
    FROM `meli-bi-data.WHOWNER.BT_VU_MODEL_RATING`
    WHERE sit_site_id = ('MLB')
      AND CRD_MODEL in ('CONSUMERS_BEHAVIOR_MXP_NEG')
      AND VALID_TO_DT = '2099-12-31'
    ) score_bhv_neg_mxp
  full join 
  (
    select 
      distinct CUS_CUST_ID 
      ,SCORE_DT 
      ,CRD_MODEL 
      ,crd_version 
      ,INTERNAL_RATING_TAG AS RATING_BHV_MXP_NO_NEG
    FROM `meli-bi-data.WHOWNER.BT_VU_MODEL_RATING`
    WHERE sit_site_id = ('MLB')
      AND CRD_MODEL in ('CONSUMERS_BEHAVIOR_MXP_NO_NEG')
      AND VALID_TO_DT = '2099-12-31'
  ) score_bhv_no_neg_mxp
    using(cus_cust_id)
;

CREATE OR REPLACE TEMP TABLE TMP_INCOME AS 
    SELECT 
        CUS_CUST_ID,
        ASSUMED_INCOME_AMT, 
        NISE_TAG
    FROM `meli-bi-data.WHOWNER.BT_VU_ASSUMED_INCOME` 
    WHERE 1 = 1
    AND VALID_TO_DT = '2099-12-31'
    AND SIT_SITE_ID = 'MLB'
;


CREATE OR REPLACE TEMP TABLE TMP_RCI_TC_TABLA AS 
    SELECT  
        RCI.CUS_CUST_ID,
        SUM(IFNULL(RCI.TEORIC_RCI_VAL,0)) AS RCI_TC_PRE_VU,
    FROM `meli-bi-data.WHOWNER.BT_VU_RCI` rci
    WHERE RCI.VALID_TO_DT = '2099-12-31' AND RCI.CURRENT_FLAG = TRUE
    AND CRD_PROD_DEF_TYPE_SK IN (3) 
    GROUP BY 1
;

CREATE OR REPLACE TEMP TABLE TMP_RCI_CC_TABLA AS
    SELECT  
        RCI.CUS_CUST_ID,
        SUM(IFNULL(RCI.CRD_CURRENT_LIMIT,0)) AS LIMITE_CONSUMO,
        SUM(IFNULL(RCI.TEORIC_RCI_VAL,0)) AS RCI_CC
    FROM `meli-bi-data.WHOWNER.BT_VU_RCI` rci
    WHERE RCI.VALID_TO_DT = '2099-12-31' AND RCI.CURRENT_FLAG = TRUE
    AND CRD_PROD_DEF_TYPE_SK IN (1,2,10) 
    GROUP BY 1
;

CREATE OR REPLACE TEMP TABLE TMP_CREDITS AS 
    SELECT 
        CUS_CUST_ID, 
        BALANCE_AMT
    FROM `meli-bi-data.WHOWNER.BT_VU_CREDIT`
    WHERE VALID_TO_DT >= '2099-12-31'
    AND CRD_PROD_DEF_TYPE_SK = 3
    AND SIT_SITE_ID = 'MLB'
    AND CRD_CREDIT_STATUS IN ('ACTIVE', 'OVERDUE')
;

CREATE OR REPLACE TEMP TABLE TMP_CAPTURA_SALDO AS
  SELECT 
    DISTINCT CUS_CUST_ID, 
    INTERNAL_RATING_TAG AS RATING_CAPTURA_SALDO
  FROM `meli-bi-data.WHOWNER.BT_VU_MODEL_RATING` MRT
  WHERE MRT.SIT_SITE_ID = 'MLB'
  AND MRT.CRD_MODEL = 'CONSUMERS_CAPTURA_SALDO_TC'
  AND MRT.VALID_TO_DT >= '2099-12-31'
  AND INTERNAL_RATING_TAG IN ('I','II') ---- UNICAMENTE LOS QUE TIENEN MAS CHANCES DE CAPTURAR SOW
;

--tabla que define cual es la priorizacion del usuario en base a las 5 variables
CREATE OR REPLACE TEMP TABLE TMP_CONVICENCIA AS
    SELECT
        *
    FROM  `WHOWNER.LK_RBA_MLB_TC_CC_CONVIVENCIA`
;

-- !! VALIDAR TABLA DATAMESH
--tabla con los topes conjuntos por politica
CREATE OR REPLACE TEMP TABLE TMP_TOPE AS 
    SELECT
        *
    FROM `meli-bi-data.SBOX_CREDITS_SB.BA_CC_MLB_PARAMETRIA_TOPES_CONJUNTOS_20250430_AGONZALEZ`
;

-- !! VALIDAR TABLA DATAMESH
--si son repeat esta le miro esta parametrica de % 
CREATE OR REPLACE TEMP TABLE TMP_PARAMETRIA AS 
    SELECT 
        *
    FROM `meli-bi-data.SBOX_CREDITS_SB.BA_CC_MLB_PARAMETRIA_PRIORIZACION_20250430_AGONZALEZ`
    ;


CREATE OR REPLACE TEMP TABLE TMP_TABLA_TC AS 
    SELECT
        TMP_KILLERS.CUS_CUST_ID,

        RK_2799 TC_ACEPTADA, 
        RK_2923 TC_FULL,
        RK_2798 TC_ACTIVA,

        CASE 
            WHEN RK_10058 IS TRUE -- SIN INGRESOS
            AND RK_2791 IS TRUE -- BLACKLIST
            AND RK_3500 IS TRUE -- RESTRICCIONES MELI
            AND RK_2793 IS TRUE -- CRED PROP CANCELADA
            AND RK_2794 IS TRUE -- PERMANENTEMENTE BLOQUEADO
            AND RK_2795 IS TRUE -- TRANSICIONAL BLOQUEADO
            AND RK_2796 IS TRUE -- RESTRUCTURACION DEUDA
            AND RK_1970 IS TRUE -- SIN CPF
            AND RK_2038 IS TRUE -- MENOR EDAD
            AND RK_84322 IS TRUE -- OVERDUE
            AND RK_1971 IS TRUE -- ATRASO OPF
            AND RK_2797 IS TRUE -- STATUS CANCELADA
            AND RK_2041 IS TRUE -- DESACTIVADA OFERTAS UPSELL
            AND RK_71870 IS TRUE -- ATRASO SCR
            THEN TRUE ELSE FALSE 
        END AS REGLAS_DURAS,

        RK_5100 RATING_EXTERNO_G,

        RK_5099 ULTIMO_SCORE_BHV, 
        RK_151247 PAGO_TOTAL, 

        CASE 
            WHEN RK_2914 IS TRUE -- ULT DOWNSELL LC
            AND RK_116070 IS TRUE -- LC-60d_RECENTLY_CREATED
            AND RK_162128 IS TRUE -- 90D-ULT-UPSELL-ORIGINACION-MXP
            THEN TRUE ELSE FALSE 
        END AS ENCENDIDO_CONVIVENCIA_CC,

        CASE 
            WHEN RK_195521 IS TRUE -- K-SEL-ESTADO-1ER-CUOTA-CF
            AND RK_195771 IS TRUE -- -SEL-ATRASO-CF-90D-EVER
            THEN TRUE ELSE FALSE 
        END AS CONVIVENCIA_SELLERS,

        rk_2918 ultimo_downsell,

        rk_131889 pix_apuestas,
        rk_131890 pix_new,
        rk_197867 pix_pct_new,

        rk_84820 killer_seguros,

        CASE 
            WHEN RK_181538 IS TRUE -- 60D_ULT_UPSELL_TC_ANTIG_4-12M
            AND RK_181537 IS TRUE -- 90D_ULT_UPSELL_TC_ANTIG_12-24M
            AND RK_181536 IS TRUE -- 120D_ULT_UPSELL_TC_ANTIG_24M
            THEN TRUE ELSE FALSE 
        END AS REGLA_DESCANSO,

        rk_126201 AS FLAG_USO_TOTAL_10,

        CASE
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 360 THEN
                CASE
                    WHEN (BALANCE_AMT / TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD) > 0.1 THEN TRUE
                    ELSE FALSE
                END
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 540 THEN
                CASE
                    WHEN (BALANCE_AMT / TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD) > 0.15 THEN TRUE
                    ELSE FALSE 
                END
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY > 540 THEN ---- ATUALIZADO. VALIDAR KILLER EOC
                CASE
                    WHEN (BALANCE_AMT / TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD) > 0.2 THEN TRUE
                    ELSE FALSE
                END
            ELSE FALSE
        END AS FLAG_USO_TOTAL_BAU_MANUAL,

        RK_199284 AS FLAG_USO_TOTAL_BAU,

        RK_158874 ANTIGUEDAD_MINIMA_4M,
        RK_31249 KILLER_SELLERS, 

        RK_234806 FLAG_VIP_MP,
        RK_133134 FLAG_VIPS_MKTPLACE,

        -- desde nov sacamos el killer plat_12
        CASE WHEN (NISE = 'PLATINUM' AND TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 360) THEN TRUE ELSE FALSE END AS PLATINUM_12,

        CASE 
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 120 THEN 'a.4m'
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 360 THEN 'b.4m-12m'
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 540 THEN 'c.12m-18m'
            WHEN TMP_POLITICA_MP.WANDA__FULL_TC_ACTIVE_DAYS_SINCE_QTY < 720 THEN 'd.18m-24m'
        ELSE 'e.>24m' END AS ANTIGUEDAD,

        -- NISE E INCOME
        TMP_POLITICA_MP.NISE,

        case 
            when tmp_politica_mp.nise in ('BRONZE','SILVER') then 'a.Silver/Bronze' 
            when tmp_politica_mp.nise in ('GOLD', 'PLATINUM') then 'b.Gold/Plat'
        else 'c.Sin Nise' end as nise_agrupado,

        case 
            when tmp_politica_mp.nise = 'BRONZE' then 'a.bronze'
            when tmp_politica_mp.nise = 'SILVER' then 'b.silver'
            when tmp_politica_mp.nise = 'GOLD' then 'c.gold'
            when tmp_politica_mp.nise = 'PLATINUM' then 'd.platinum' 
        end as nise_ordenado,

        -- KILLER USERS POLITICA JOURNEY PRIMER ANO
        CASE 
          WHEN tmp_politica_mp.nise = 'BRONZE' and TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD < 1400 and RIGHT(cast(tmp_politica_mp.cus_cust_id as string), 1) > '3' then 'a. bronze/1400'
          WHEN tmp_politica_mp.nise = 'SILVER' and TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD < 2200 and RIGHT(cast(tmp_politica_mp.cus_cust_id as string), 1) > '3' then 'b. silver/2200'
          ELSE 'z. ok'
        END AS flag_exclusion_nise,

        ASSUMED_INCOME_AMT,

        -- DATOS CC --
        CASE WHEN TMP_TABLA_CC.CUS_CUST_ID IS NOT NULL THEN TRUE
            ELSE FALSE END AS FLAG_REPEAT,

        CASE
            WHEN TMP_TABLA_CC.NUEVO_RATING_MXP_PARA_PRICING IS NOT NULL THEN TMP_TABLA_CC.NUEVO_RATING_MXP_PARA_PRICING
            ELSE 'Sin Rating bhv'
        END AS RATING_BHV_CC,

        TMP_POLITICA_MP.WANDA__TEORIC_RCI_VAL RCI_CC, 

        -- RATING --
        CASE
            WHEN TMP_POLITICA_MP.INTERNAL_RATING_BEHAVIOR_TC IS NOT NULL THEN TMP_POLITICA_MP.INTERNAL_RATING_BEHAVIOR_TC
            ELSE 'Sin Rating bhv TC'
        END AS RATING_BHV_TC,
        TMP_POLITICA_MP.INTERNAL_RATING_UPSELL_TC RATING_UPSELL_TC,

        -- MULTIPLICADORES NOMINALES --
        CASE WHEN 
            -- VIP_MP
                RK_234806 IS TRUE THEN TMP_POLITICA_MP.MULTIP_NOM_UPS   
            WHEN 
            -- VIPS_MKTPLACE
                RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.MULTIP_NOM_UPS

            -- BAU - CAPTURA SALDO
            -- WHEN IFNULL(TMP_CAPTURA_SALDO.RATING_CAPTURA_SALDO, '0') IN ('I', 'II') AND MOD(TMP_POLITICA_BAU.CUS_CUST_ID, 2) = 0 THEN TMP_POLITICA_BAU.MULTIP_NOM_UPS * 1.2

            -- BAU
            ELSE TMP_POLITICA_BAU.MULTIP_NOM_UPS 
            
        END AS MULTIPLICADOR_NOMINAL,

        -- marca para users que van tener buff de 20% en el multiplicador
        -- CASE 
        --     WHEN RK_234806 IS FALSE AND RK_133134 IS FALSE AND 
        --         (
        --             IFNULL(TMP_CAPTURA_SALDO.RATING_CAPTURA_SALDO, '0') IN ('I', 'II') AND MOD(TMP_POLITICA_BAU.CUS_CUST_ID, 2) = 0 -- captura saldo
        --             OR (BALANCE_AMT/TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD) > 0.6 -- black friday
        --         )
        --         THEN 1 ELSE 0 
        -- END AS FLAG_BUFF_20_TEST,


        CASE 
            -- VIP_MP
            WHEN RK_234806 IS TRUE THEN TMP_POLITICA_MP.LIMITE_MULTIPLICADOR   
            -- VIPS_MKTPLACE
            WHEN RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.LIMITE_MULTIPLICADOR
            -- BAU -- CAPTURA SALDO
            -- WHEN IFNULL(TMP_CAPTURA_SALDO.RATING_CAPTURA_SALDO, '0') IN ('I', 'II') AND MOD(TMP_POLITICA_BAU.CUS_CUST_ID, 2) = 0 THEN TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD * TMP_POLITICA_BAU.MULTIP_NOM_UPS * 1.2
            -- BAU
            ELSE TMP_POLITICA_BAU.LIMITE_MULTIPLICADOR 
        END AS LIMITE_MULTIPLICADOR,

        -- LIMITES --
        TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD CURRENT_LIMIT,
        CASE 
            WHEN TMP_POLITICA_MP.WANDA__CCARD_OVC_ADD_PERCENTAGE > 0 THEN TRUE
            ELSE FALSE 
        END AS FLAG_OVERLIMIT,

        CASE 
            WHEN LIMITE_CONSUMO IS NULL THEN 0 
            ELSE LIMITE_CONSUMO 
        END AS LIMITE_CC,

        (CASE 
            WHEN LIMITE_CONSUMO IS NULL THEN 0 
            ELSE LIMITE_CONSUMO END 
            + TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD
        ) LIMITE_TOTAL,

        -- PAGO MIN Y USO --
        CASE 
            -- VIP_MP
            WHEN RK_234806 IS TRUE THEN TMP_POLITICA_MP.PAGO_MIN_TC_TEORICO   
            -- VIPS_MKTPLACE
            WHEN RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.PAGO_MIN_TC_TEORICO
            -- BAU
            ELSE TMP_POLITICA_BAU.PAGO_MIN_TC_TEORICO 
        END AS PAGO_MIN_TC_TEORICO,

        CASE 
            -- VIP_MP
            WHEN RK_234806 IS TRUE THEN TMP_POLITICA_MP.PAGO_MIN_TC_UPS   
            -- VIPS_MKTPLACE
            WHEN RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.PAGO_MIN_TC_UPS
            -- BAU
            ELSE TMP_POLITICA_BAU.PAGO_MIN_TC_UPS 
        END AS PAGO_MIN_TC,

        CASE 
            -- VIP_MP
            WHEN RK_234806 IS TRUE THEN TMP_POLITICA_MP.NIVEL_USO_TC_TEORICO   
            -- VIPS_MKTPLACE
            WHEN RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.NIVEL_USO_TC_TEORICO
            -- BAU
            ELSE TMP_POLITICA_BAU.NIVEL_USO_TC_TEORICO 
        END AS NIVEL_USO_TC_TEORICO,

        CASE 
            -- VIP_MP
            WHEN RK_234806 IS TRUE THEN TMP_POLITICA_MP.NIVEL_USO_TC_UPS   
            -- VIPS_MKTPLACE
            WHEN RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.NIVEL_USO_TC_UPS
            -- BAU
            ELSE TMP_POLITICA_BAU.NIVEL_USO_TC_UPS 
        END AS NIVEL_USO_TC,

        BALANCE_AMT/TMP_POLITICA_MP.WANDA__CURRENT_LIMIT_CCARD AS USO_TOTAL,

        -- RCI --
        TMP_POLITICA_MP.RCI_CONJUNTA RCI_CONJUNTA_PRE,
        (TMP_POLITICA_MP.RCI_CONJUNTA - TMP_POLITICA_MP.WANDA__TEORIC_RCI_VAL) RCI_TC_PRE_EOC,
        RCI_TC_PRE_VU,

        -- RATING
        CASE 
            -- VIP_MP
            WHEN RK_234806 IS TRUE THEN TMP_POLITICA_MP.CLUSTER > 0
            -- VIPS_MKTPLACE
            WHEN RK_133134 IS TRUE THEN TMP_POLITICA_MKTPLACE.CLUSTER > 0
            -- BAU
            ELSE TMP_POLITICA_BAU.CLUSTER > 0  
        END AS RATING,

        IFNULL(TMP_CAPTURA_SALDO.RATING_CAPTURA_SALDO, '0') AS RATING_CAPTURA_SALDO

    FROM TMP_KILLERS
    LEFT JOIN TMP_POLITICA_MP        ON TMP_KILLERS.CUS_CUST_ID = TMP_POLITICA_MP.CUS_CUST_ID 
    LEFT JOIN TMP_POLITICA_MKTPLACE  ON TMP_KILLERS.CUS_CUST_ID = TMP_POLITICA_MKTPLACE.CUS_CUST_ID
    LEFT JOIN TMP_POLITICA_BAU       ON TMP_KILLERS.CUS_CUST_ID = TMP_POLITICA_BAU.CUS_CUST_ID
    LEFT JOIN TMP_TABLA_CC           ON TMP_KILLERS.CUS_CUST_ID = TMP_TABLA_CC.CUS_CUST_ID
    LEFT JOIN TMP_INCOME             ON TMP_KILLERS.CUS_CUST_ID = TMP_INCOME.CUS_CUST_ID
    LEFT JOIN TMP_RCI_TC_TABLA       ON TMP_KILLERS.CUS_CUST_ID = TMP_RCI_TC_TABLA.CUS_CUST_ID
    LEFT JOIN TMP_CREDITS            ON TMP_KILLERS.CUS_CUST_ID = TMP_CREDITS.CUS_CUST_ID
    LEFT JOIN TMP_CAPTURA_SALDO      ON TMP_KILLERS.CUS_CUST_ID = TMP_CAPTURA_SALDO.CUS_CUST_ID
    LEFT JOIN TMP_RCI_CC_TABLA       ON TMP_KILLERS.CUS_CUST_ID = TMP_RCI_CC_TABLA.CUS_CUST_ID
;

--- TABLA PRIORIZACION ---
CREATE OR REPLACE TEMP TABLE TMP_PRIORIZACION AS

    SELECT 
        A.*,
        TMP_CONVICENCIA.CC CONV_CC,
        TMP_CONVICENCIA.TC CONV_TC,
        TMP_PARAMETRIA.PRIORIZACION,
        TMP_PARAMETRIA.PRIORIZACION_DETALLE,
        TMP_PARAMETRIA.PORC_CC PORC_CC,
        TMP_PARAMETRIA.PORC_TC PORC_TC,
        TMP_TOPE.NIVEL_RIESGO NIVEL_RIESGO_CONJUNTO,
        TMP_TOPE.RCI_TOPE TOPE_CONJUNTO,

        --- SI EL USUARIO ES ACT, EL TOPE DE CC ES 0 Y EL TOPE DE TC ES EL MAX RCI CONJUNTA
        CASE 
            WHEN FLAG_REPEAT = TRUE THEN TMP_TOPE.RCI_TOPE * TMP_PARAMETRIA.PORC_CC
            ELSE 0
        END AS TOPE_CC,
        CASE 
            WHEN FLAG_REPEAT = TRUE THEN TMP_TOPE.RCI_TOPE * TMP_PARAMETRIA.PORC_TC
            ELSE TMP_TOPE.RCI_TOPE
        END AS TOPE_TC,

        MULTI_MAX MULTIPLICADOR_NOMINAL_CONJUNTO,
        LIMITE_TOTAL * MULTI_MAX LIMITE_NOMINAL_CONJUNTO,
        ((LIMITE_TOTAL * MULTI_MAX) - LIMITE_TOTAL) AS AUMENTO_NOMINAL_CONJUNTO,


        --- AUMENTO NOMINAL TC: SI EL USUARIO ES REPEAT: AUMENTO NOMINAL CONJUNTO * PORC TC REPEAT // SI EL USUARIO ES ACT: AUMENTO NOMINAL CONJUNTO
        CASE 
            WHEN FLAG_REPEAT = TRUE THEN ((LIMITE_TOTAL * MULTI_MAX) - LIMITE_TOTAL) * TMP_PARAMETRIA.PORC_TC
            ELSE ((LIMITE_TOTAL * MULTI_MAX) - LIMITE_TOTAL)
        END AS AUMENTO_NOMINAL_TC,

        FROM TMP_TABLA_TC A
        LEFT JOIN TMP_CONVICENCIA 
            ON TMP_CONVICENCIA.CUS_CUST_ID = A.CUS_CUST_ID
        LEFT JOIN  TMP_TOPE
            ON TMP_TOPE.RATING_BHV_CC = A.RATING_BHV_CC
            AND TMP_TOPE.RATING_BHV_TC = A.RATING_BHV_TC
            AND TMP_TOPE.CLUSTER= (CASE WHEN FLAG_VIP_MP IS TRUE OR FLAG_VIPS_MKTPLACE IS TRUE THEN "VIP" ELSE "BAU" END)
        LEFT JOIN TMP_PARAMETRIA
            ON TMP_PARAMETRIA.NISE_AGRUPADO = A.NISE_AGRUPADO
            AND SAFE_CAST(TMP_PARAMETRIA.CC AS INT64) = SAFE_CAST(TMP_CONVICENCIA.CC AS INT64) 
            AND TMP_PARAMETRIA.TC = TMP_CONVICENCIA.TC 
;

---- funnel primera parte ----

    SELECT 
        COUNT (CUS_CUST_ID), 
        COUNT (DISTINCT CUS_CUST_ID), 
        -- FLAG_REPEAT
    FROM TMP_PRIORIZACION 
    WHERE 1=1
    -- KILLERS QUE APLICAN A LAS 3 POLÍTICAS
    AND TC_ACEPTADA IS TRUE
    AND TC_FULL IS TRUE 
    AND TC_ACTIVA IS TRUE
    AND ANTIGUEDAD_MINIMA_4M IS TRUE
    AND REGLAS_DURAS IS TRUE
    AND ULTIMO_SCORE_BHV IS TRUE
    AND PAGO_TOTAL IS TRUE
    AND ENCENDIDO_CONVIVENCIA_CC IS TRUE
    AND CONVIVENCIA_SELLERS IS TRUE
    AND ULTIMO_DOWNSELL IS TRUE
    AND PIX_APUESTAS IS TRUE
    AND PIX_NEW IS TRUE
    AND PIX_PCT_NEW IS TRUE
    AND KILLER_SEGUROS IS TRUE 
    AND REGLA_DESCANSO IS TRUE
    AND flag_exclusion_nise NOT IN ('a. bronze/1400', 'b. silver/2200')
    AND FLAG_VIPS_MKTPLACE IS FALSE
    AND FLAG_VIP_MP IS FALSE
    AND RATING IS TRUE
    GROUP BY ALL
;

-- KILLER AUTOFONDEO
CREATE OR REPLACE TEMP TABLE AUTOFONDEO AS 
  SELECT
    CUS_CUST_ID,
    FALSE AS KILLER_AUTOFONDEO
  FROM `SBOX_CREDITS_SB.RBA_TC_MLB_AUTOFONDEO_12M_MABANUS`
;

--- TABLA TOPES CONJUNTOS ---

CREATE OR REPLACE TEMP TABLE TMP_TOPES AS

    SELECT
        A.*,
        -- KILLER RCI CONJ > TOPE
        CASE WHEN RCI_CONJUNTA_PRE >= TOPE_CONJUNTO THEN TRUE ELSE FALSE END AS FLAG_TOPE_CONJ_RCI,

        -- CALCULO LOS % DE DISTRIBUCION EN BASE AL DISPONIBLE DE RCI (PARTO DEL OTRO PRODUCTO Y DESPUES KILLEO LOS QUE SE PASAN POR EL MIO)
        GREATEST (TOPE_CC, RCI_CC)/TOPE_CONJUNTO PORC_CC_DISPONIBLE, 

        (1- (GREATEST (TOPE_CC, RCI_CC)/TOPE_CONJUNTO)) PORC_TC_DISPONIBLE,

        -- CALCULO LOS NUEVOS TOPES DE RCI EN BASE AL DISPONIBLE
        TOPE_CONJUNTO * (GREATEST (TOPE_CC, RCI_CC)/TOPE_CONJUNTO) TOPE_CC_DISPONIBLE,

        TOPE_CONJUNTO * ((1- (GREATEST (TOPE_CC, RCI_CC)/TOPE_CONJUNTO))) TOPE_TC_DISPONIBLE,

        -- KILLER RCI TC > TOPE_TC_DISPONIBLE
        CASE WHEN RCI_TC_PRE_EOC >= (TOPE_CONJUNTO * ((1- (GREATEST (TOPE_CC, RCI_CC)/TOPE_CONJUNTO)))) THEN TRUE ELSE FALSE END AS FLAG_TOPE_TC_RCI,
        (CURRENT_LIMIT + AUMENTO_NOMINAL_TC) AS LIMITE_NOMINAL_TC,

        IFNULL(AUTOFONDEO.KILLER_AUTOFONDEO, TRUE) AS KILLER_AUTOFONDEO,

        CASE 
        -- VIP
            WHEN FLAG_VIP_MP IS TRUE OR FLAG_VIPS_MKTPLACE IS TRUE THEN 
                CASE
                    WHEN NISE_ORDENADO IN ('a.bronze') AND RATING_BHV_TC IN ('A', 'B') THEN 20000
                    WHEN NISE_ORDENADO IN ('a.bronze') AND RATING_BHV_TC IN ('C', 'D', 'E', 'F') THEN 15000
                    WHEN NISE_ORDENADO IN ('b.silver') AND RATING_BHV_TC IN ('A', 'B') THEN 25000
                    WHEN NISE_ORDENADO IN ('b.silver') AND RATING_BHV_TC IN ('C', 'D', 'E') THEN 20000
                    WHEN NISE_ORDENADO IN ('c.gold') AND RATING_BHV_TC IN ('A', 'B') THEN 30000
                    WHEN NISE_ORDENADO IN ('c.gold') AND RATING_BHV_TC IN ('C', 'D', 'E', 'F')THEN 25000
                    WHEN NISE_ORDENADO IN ('d.platinum') AND RATING_BHV_TC IN ('A', 'B')THEN 35000
                    WHEN NISE_ORDENADO IN ('d.platinum') AND RATING_BHV_TC IN ('C', 'D', 'E', 'F')THEN 30000
                    ELSE NULL 
                END
        -- BAU
            ELSE 
                CASE 
                    WHEN NISE_ORDENADO IN ('a.bronze') AND RATING_BHV_TC IN ('A', 'B') THEN 20000
                    WHEN NISE_ORDENADO IN ('a.bronze') AND RATING_BHV_TC IN ('C', 'D', 'E') THEN 15000
                    WHEN NISE_ORDENADO IN ('b.silver') AND RATING_BHV_TC IN ('A', 'B') THEN 25000
                    WHEN NISE_ORDENADO IN ('b.silver') AND RATING_BHV_TC IN ('C', 'D', 'E') THEN 20000
                    WHEN NISE_ORDENADO IN ('c.gold') AND RATING_BHV_TC IN ('A', 'B') THEN 27000
                    WHEN NISE_ORDENADO IN ('c.gold') AND RATING_BHV_TC IN ('C', 'D', 'E')THEN 25000
                    WHEN NISE_ORDENADO IN ('d.platinum') AND RATING_BHV_TC IN ('A', 'B')THEN 30000
                    WHEN NISE_ORDENADO IN ('d.platinum') AND RATING_BHV_TC IN ('C', 'D', 'E')THEN 27000
                    ELSE NULL 
                END
            END 
        AS LIMITE_NOMINAL_TC_INTERNO,
        -- LIMITE RCI: TOPE_TC_DISPONIBLE * INCOME / USO * PAGO_MIN = LIMITE 
        (((TOPE_CONJUNTO * ((1- (GREATEST (TOPE_CC, RCI_CC)/TOPE_CONJUNTO)))) * ASSUMED_INCOME_AMT) / (NIVEL_USO_TC * PAGO_MIN_TC)) LIMITE_RCI

    FROM TMP_PRIORIZACION A
    LEFT JOIN AUTOFONDEO USING(CUS_CUST_ID)

    WHERE 1=1

    -- KILLERS QUE APLICAN A LAS 3 POLÍTICAS
    AND TC_ACEPTADA IS TRUE
    AND TC_FULL IS TRUE 
    AND TC_ACTIVA IS TRUE
    AND ANTIGUEDAD_MINIMA_4M IS TRUE
    AND REGLAS_DURAS IS TRUE
    AND ULTIMO_SCORE_BHV IS TRUE
    AND PAGO_TOTAL IS TRUE

    -- AND CONVIVENCIA_CC IS TRUE
    AND ENCENDIDO_CONVIVENCIA_CC IS TRUE
    AND CONVIVENCIA_SELLERS IS TRUE
    AND ULTIMO_DOWNSELL IS TRUE

    AND PIX_APUESTAS IS TRUE
    AND PIX_NEW IS TRUE
    AND PIX_PCT_NEW IS TRUE
    AND KILLER_SEGUROS IS TRUE 

    AND REGLA_DESCANSO IS TRUE

    AND RATING IS TRUE

    AND flag_exclusion_nise not in ('a. bronze/1400', 'b. silver/2200')
    ;




---- FUNNEL SEGUNDA PARTE ----
SELECT 
    COUNT (CUS_CUST_ID),
    COUNT (DISTINCT CUS_CUST_ID),
FROM TMP_TOPES A
WHERE 1=1
    AND FLAG_VIP_MP IS TRUE
    -- AND FLAG_VIPS_MKTPLACE IS TRUE
    -- AND FLAG_USO_TOTAL_BAU IS TRUE
    AND FLAG_USO_TOTAL_10 IS TRUE
    AND FLAG_TOPE_CONJ_RCI IS FALSE
    AND FLAG_TOPE_TC_RCI IS FALSE
    AND KILLER_SELLERS IS TRUE
    -- AND PLATINUM_12 IS FALSE
    
    -- TEST CAPTURA SALDO
    AND RATING_UPSELL_TC NOT IN ('E', 'G')
    AND RATING_BHV_TC NOT IN ('F')

    -- AND IFNULL(RATING_CAPTURA_SALDO, '0') NOT IN ('I', 'II')

    AND KILLER_AUTOFONDEO IS TRUE
;



--- TABLA LIMITES ---

CREATE OR REPLACE TEMP TABLE TMP_LIMITE AS

    SELECT
        A.*,
        CASE 
            WHEN ROUND (LEAST (LIMITE_MULTIPLICADOR, LIMITE_RCI, LIMITE_NOMINAL_TC), -2)  > LIMITE_NOMINAL_TC_INTERNO THEN LIMITE_NOMINAL_TC_INTERNO
            ELSE ROUND (LEAST (LIMITE_MULTIPLICADOR, LIMITE_RCI, LIMITE_NOMINAL_TC), -2) 
        END AS LIMITE_FINAL,

        CASE 
            WHEN ROUND (LEAST (LIMITE_MULTIPLICADOR, LIMITE_RCI, LIMITE_NOMINAL_TC), -2) > LIMITE_NOMINAL_TC THEN 'limite_nominal_tc'
            ELSE
                CASE 
                    WHEN ROUND (LEAST (LIMITE_MULTIPLICADOR, LIMITE_RCI, LIMITE_NOMINAL_TC), -2) = ROUND (LIMITE_MULTIPLICADOR, -2) THEN 'limite_multiplicador'
                    WHEN ROUND (LEAST (LIMITE_MULTIPLICADOR, LIMITE_RCI, LIMITE_NOMINAL_TC), -2) = ROUND (LIMITE_RCI,-2) THEN 'limite_rci'
                    WHEN ROUND (LEAST (LIMITE_MULTIPLICADOR, LIMITE_RCI, LIMITE_NOMINAL_TC), -2) = ROUND (LIMITE_NOMINAL_TC,-2) THEN 'limite_nominal_tc'
                    ELSE 'otro_caso' 
                END
        END AS ORIGEN_LIMITE_FINAL
    FROM TMP_TOPES A
    WHERE 1=1
    AND FLAG_TOPE_CONJ_RCI IS FALSE
    AND FLAG_TOPE_TC_RCI IS FALSE
    AND KILLER_AUTOFONDEO IS TRUE;

--- TABLA BASES ---

CREATE OR REPLACE TEMP TABLE TMP_BASES AS

    SELECT
        A.*,
        CASE 
            WHEN ((LIMITE_FINAL - CURRENT_LIMIT) >= 100 OR LIMITE_FINAL >= CURRENT_LIMIT * 0.1) THEN FALSE 
            ELSE TRUE 
        END AS FLAG_UPSELL_INSUFICIENTE, 

        ((LIMITE_FINAL * NIVEL_USO_TC * PAGO_MIN_TC) / ASSUMED_INCOME_AMT) RCI_TC_POST,

        (RCI_CC + ((LIMITE_FINAL * NIVEL_USO_TC * PAGO_MIN_TC) / ASSUMED_INCOME_AMT)) RCI_CONJUNTA_POST

    FROM 
    (
        /*
        em dez no vamos hacer test captura de saldo
        --CAPTURA SALDO -- 1
        (
            SELECT 
                *,
                'SOW aumento exposicion' AS UPSELL
            FROM TMP_LIMITE
            WHERE 1=1
            AND FLAG_VIPS_MKTPLACE IS FALSE
            AND FLAG_VIP_MP IS FALSE 
            -- AND PLATINUM_12 IS FALSE 
            AND KILLER_SELLERS IS TRUE
            AND FLAG_USO_TOTAL_BAU IS TRUE
            
            -- TEST CAPTURA SALDO
            AND RATING_UPSELL_TC NOT IN ('E', 'G')
            AND RATING_BHV_TC NOT IN ('F')
            AND IFNULL(RATING_CAPTURA_SALDO, '0') IN ('I', 'II')
        )

        UNION ALL

        --CAPTURA SALDO -- 2
        (
            SELECT 
                *,
                'SOW riesgo medio' AS UPSELL
            FROM TMP_LIMITE
            WHERE 1=1
            AND (FLAG_VIP_MP IS TRUE OR FLAG_VIPS_MKTPLACE IS TRUE)
            AND KILLER_SELLERS IS TRUE
            AND FLAG_USO_TOTAL_10 IS TRUE
            
            -- TEST CAPTURA SALDO            
            AND (RATING_BHV_TC IN ('F') OR RATING_UPSELL_TC IN ('E', 'G'))
            AND IFNULL(RATING_CAPTURA_SALDO, '0') IN ('I', 'II')
        )

        UNION ALL

        */
        --VIPS MP
        (
            SELECT 
                *,
                'vips mp' AS UPSELL
            FROM TMP_LIMITE
            WHERE 1=1
            AND FLAG_VIP_MP IS TRUE 
            AND KILLER_SELLERS IS TRUE
            AND FLAG_USO_TOTAL_10 IS TRUE
            
            -- TEST CAPTURA SALDO (saca riesgo medio)
            AND RATING_UPSELL_TC NOT IN ('E', 'G')
            AND RATING_BHV_TC NOT IN ('F')
        )

        UNION ALL
        
        --VIPS MKTPLACE
        (
            SELECT 
                *,
                'vips mktplace' AS UPSELL
            FROM TMP_LIMITE
            WHERE 1=1
            AND FLAG_VIPS_MKTPLACE IS TRUE
            AND FLAG_VIP_MP IS FALSE
            AND FLAG_USO_TOTAL_10 IS TRUE

            -- TEST CAPTURA SALDO (saca riesgo medio)
            AND RATING_UPSELL_TC NOT IN ('E', 'G')
            AND RATING_BHV_TC NOT IN ('F')
        )

        UNION ALL

        --BAU
        (
            SELECT 
                *,
                'bau' AS UPSELL
            FROM TMP_LIMITE
            WHERE 1=1
            AND FLAG_VIPS_MKTPLACE IS FALSE 
            AND FLAG_VIP_MP IS FALSE
            -- AND PLATINUM_12 IS FALSE 
            AND KILLER_SELLERS IS TRUE
            AND FLAG_USO_TOTAL_BAU IS TRUE

            -- TEST CAPTURA SALDO (saca riesgo medio)kt
            AND RATING_BHV_TC NOT IN ('F')
            AND RATING_UPSELL_TC NOT IN ('E', 'G')
            -- AND IFNULL(RATING_CAPTURA_SALDO, '0') NOT IN ('I', 'II')
        ) 
    ) A
    WHERE LIMITE_FINAL > CURRENT_LIMIT
;

CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_FUNNEL_20251210_GUBELARMINO` AS
SELECT * FROM TMP_PRIORIZACION
;


CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GUBELARMINO` AS
SELECT 
  * 
  ,case
    when RATING_BHV_TC IN ('A', 'B') AND RATING_UPSELL_TC IN ('A', 'B') THEN 'a. Muy bajo'

    when (RATING_BHV_TC IN ('C', 'D') AND RATING_UPSELL_TC IN ('C', 'D', 'E')) 
      OR (RATING_BHV_TC IN ('C', 'D') AND RATING_UPSELL_TC IN ('A', 'B'))
      OR (RATING_BHV_TC IN ('A', 'B') AND RATING_UPSELL_TC IN ('C', 'D', 'E')) 
    THEN 'b. Bajo'

    when (RATING_BHV_TC IN ('E', 'F') AND RATING_UPSELL_TC IN ('G', 'J')) 
      OR (RATING_BHV_TC IN ('E', 'F') AND RATING_UPSELL_TC IN ('A', 'B', 'C', 'D', 'E')) 
      OR (RATING_BHV_TC IN ('A', 'B', 'C', 'D') AND RATING_UPSELL_TC IN ('G', 'J')) 
    THEN 'c. Medio'
  end as nivel_riesgo
FROM TMP_BASES
;



-- ------ GC / GI ------
CREATE OR REPLACE TEMP TABLE TABLA_FILAS AS
SELECT 
    A.*,
    ROW_NUMBER() OVER (PARTITION BY RATING_BHV_TC ORDER BY CURRENT_LIMIT ASC) AS FILA,
FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GUBELARMINO` A
WHERE 1=1 
    AND RATING_BHV_TC NOT IN ('E')
    AND IF(NISE = 'PLATINUM' and ANTIGUEDAD not in ('a.4m', 'b.4m-12m') and upsell = 'vips mktplace',1,0) = 0
;


CREATE OR REPLACE TEMP TABLE TABLA_FILAS_GI AS
SELECT A.*,
        CASE WHEN UPSELL = 'bau' THEN
            CASE 
                WHEN RATING_BHV_TC IN ('A') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
                WHEN RATING_BHV_TC IN ('A') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
                WHEN RATING_BHV_TC IN ('B') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
                WHEN RATING_BHV_TC IN ('B') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
                WHEN RATING_BHV_TC IN ('C') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
                WHEN RATING_BHV_TC IN ('C') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
                WHEN RATING_BHV_TC IN ('D') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
                WHEN RATING_BHV_TC IN ('D') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
                WHEN RATING_BHV_TC IN ('E') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
                WHEN RATING_BHV_TC IN ('E') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI' 
            ELSE 'NADA'
            END 
        WHEN UPSELL = 'vips mktplace' THEN
            CASE 
            WHEN RATING_BHV_TC IN ('A') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('A') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('B') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('B') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('C') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('C') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('D') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('D') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('E') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('E') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            ELSE 'NADA'
            END 
        WHEN UPSELL = 'vips mp' THEN
            CASE 
            WHEN RATING_BHV_TC IN ('A') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('A') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('B') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('B') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('C') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('C') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('D') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('D') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('E') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('E') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            WHEN RATING_BHV_TC IN ('F') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) >= '80' THEN 'GC'
            WHEN RATING_BHV_TC IN ('F') AND RIGHT(CAST(CUS_CUST_ID AS STRING),2) <  '80' THEN 'GI'
            ELSE 'NADA'
            END
        END AS GRUPOS
      FROM TABLA_FILAS A;


CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251210_GI_GC_GUBELARMINO` AS
SELECT * FROM TABLA_FILAS_GI
;