DECLARE MAX_DT DATE;

-- SET MAX_DT = '2024-01-01';
SET MAX_DT = (select max(actionable_dt) from `SBOX_CREDITS_SB.RBA_TC_MLB_SEGUIMIENTO_UPSELL_DOWNSELL_VU_CAMPAIGN_GUBELARMINO`);

-- CREATE OR REPLACE TABLE `SBOX_CREDITS_SB.RBA_TC_MLB_SEGUIMIENTO_UPSELL_DOWNSELL_VU_CAMPAIGN_GUBELARMINO` AS
INSERT INTO `SBOX_CREDITS_SB.RBA_TC_MLB_SEGUIMIENTO_UPSELL_DOWNSELL_VU_CAMPAIGN_GUBELARMINO` 


with VU_CAMPAIGN as (
select
  cus_cust_id,
  ACTIONABLE_DT, 
  RISK_ID, 
  CAMPAIGN_ID, 
  CAMPAIGN_GROUP_DESC, 
  CAMPAIGN_DESC, 
  CAMPAIGN_POLICY_SUBCATEGORY_DESC,
  CONTROL_GROUP_FLAG, 
  PROCESS_STATUS,
  ACTIONABLE_AMT AS LIMITE_POST,
  AUD_FROM_INTERFACE,
  AUD_INS_USR,
  IN_WHOWNER_FLAG,
  CRD_PROD_DEF_TYPE_SK,

from `WHOWNER.BT_VU_CAMPAIGN`
WHERE 1=1
  AND SIT_SITE_ID = 'MLB'
  AND ACTIONABLE_DT > MAX_DT
  AND AUD_FROM_INTERFACE NOT IN ('BT_CCARD_ELIGIBILITY_ENGINE_ACTIONABLE')
  AND RISK_ID NOT LIKE "%MTC%"
  AND
  (
    (
      (RISK_ID LIKE "%TC-UPSELL%" OR RISK_ID LIKE "%TC FULL-UPSELL%")
      AND RISK_ID NOT LIKE "%PREFERENCIAL%"
      AND RISK_ID NOT LIKE "%PORTABILIDAD%"
      -- AND CAMPAIGN_POLICY_SUBCATEGORY_DESC NOT IN ("SELLERS")
    )
    OR
    (
      (RISK_ID LIKE "%TC FULL-DOWNSELL%" OR RISK_ID LIKE "%TC-DOWNSELL%")
    )  
  )
)

, LIMIT_HIST AS (
  select
    CUS_CUST_ID, 
    CCARD_LIMIT_GENERAL,
    DATE(CCARD_LIMIT_UPDATE_DTTM) AS CCARD_LIMIT_UPDATE_DTTM
  FROM `WHOWNER.BT_CCARD_LIMIT_HIST`
  WHERE SIT_SITE_ID = 'MLB'
  AND CUS_CUST_ID IN (SELECT CUS_CUST_ID FROM VU_CAMPAIGN)
)

select
  -- *,
  CUS_CUST_ID,
  ACTIONABLE_DT,
  CCARD_LIMIT_UPDATE_DTTM,
  RISK_ID, 
  CAMPAIGN_ID, 
  CAMPAIGN_GROUP_DESC, 
  CAMPAIGN_DESC, 
  CAMPAIGN_POLICY_SUBCATEGORY_DESC,
  CONTROL_GROUP_FLAG, 
  PROCESS_STATUS,
  AUD_FROM_INTERFACE,
  AUD_INS_USR,
  IN_WHOWNER_FLAG,
  CRD_PROD_DEF_TYPE_SK,
  LIMITE_POST,
  LIMITE_PREV,
  LIMITE_POST-LIMITE_PREV AS VARIACION,
FROM (
  SELECT
    *
  FROM (
    select 
      VU_CAMPAIGN.*,
      LIMIT_HIST.CCARD_LIMIT_GENERAL AS LIMITE_PREV,
      LIMIT_HIST.CCARD_LIMIT_UPDATE_DTTM
    from VU_CAMPAIGN
    left join LIMIT_HIST
    on VU_CAMPAIGN.CUS_CUST_ID = LIMIT_HIST.CUS_CUST_ID AND ACTIONABLE_DT > CCARD_LIMIT_UPDATE_DTTM -- trazer a ultima atualizacao de limite antes do acionavel
  )
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUS_CUST_ID, CAMPAIGN_ID ORDER BY CCARD_LIMIT_UPDATE_DTTM DESC) = 1
)