###### INSERT BAU #######

#### insert 1

--`meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO`

--- IMPACTO
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'BAU', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'GESTION' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---8d652ae3-e0c1-4cb9-b110-bea44f9efd8f

-- CONTROL
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'BAU', --5 Policy
'BAU', --6 Policy Category
'BAU', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'CONTROL' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---4ccf1961-8b0a-49e8-af4f-842c9bf5a098



--- INSERT EN CEREBRO 
      
--insert GI 1

INSERT INTO `meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL`
(
  USER_ID,
  GENERAL_LIMIT,
  WITHDRAW_LIMIT,
  SITE_ID,
  PRIORITY,
  IS_UPSELL,
  CAMPAIGN_ID,
  AUD_INS_USER
)
select  
  cus_cust_id as USER_ID,
  CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
  50 as WITHDRAW_LIMIT,
  'MLB' SITE_ID,
  0 PRIORITY,
  1 IS_UPSELL,
  '8d652ae3-e0c1-4cb9-b110-bea44f9efd8f' CAMPAIGN_ID,
  'gubelarmino' AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO`
where grupos like '%GI%' and upsell = 'bau'
;



---insert GC

INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)  
select
  cus_cust_id as USER_ID,
  CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
  50 as WITHDRAW_LIMIT,
  'MLB' SITE_ID,
  0 PRIORITY,
  1 IS_UPSELL,
  '4ccf1961-8b0a-49e8-af4f-842c9bf5a098' CAMPAIGN_ID,
  CASE WHEN grupos = 'GC' THEN TRUE ELSE FALSE END AS CAMPAIGN_CONTROL_GROUP,
 'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO`
where grupos like '%GC%' and upsell = 'bau'
;




---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'4ccf1961-8b0a-49e8-af4f-842c9bf5a098' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime '2025-08-05 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO` a
where grupos like '%GC%' and upsell = 'bau') A
;


--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'8d652ae3-e0c1-4cb9-b110-bea44f9efd8f' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime '2025-08-05 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO` a
where grupos like '%GI%' and upsell = 'bau') A
;


###### INSERT VIPS MP #######

#### insert 1

--`meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO`

-- IMPACTO
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'TEST EXPOSICION', --5 Policy
'OTROS', --6 Policy Category
'VIPs MP', --7 Policy_subcategory
'N/A', --8 Policy_description
'GESTION', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'GESTION' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---81f3e2b9-82e4-401a-b046-fc7018a07a07

--CONTROL
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'IND', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'TEST EXPOSICION', --5 Policy
'OTROS', --6 Policy Category
'VIPs MP', --7 Policy_subcategory
'N/A', --8 Policy_description
'CONTROL', --9 Campaign_group
'ESTRATEGIA CONJUNTA' --10 Campaign_group_desc
);

--CHECK
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` where sit_site_id = 'MLB'and CAMPAIGN_GROUP = 'CONTROL' AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;
---a351cb5e-9d24-4d61-b46f-c8ce2522cad3


--- INSERT EN CEREBRO 
      
--insert GI 1

INSERT INTO `meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL`(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
AUD_INS_USER)
select  
cus_cust_id as USER_ID,
CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
50 as WITHDRAW_LIMIT,
'MLB' SITE_ID,
0 PRIORITY,
1 IS_UPSELL,
'81f3e2b9-82e4-401a-b046-fc7018a07a07' CAMPAIGN_ID,
'gubelarmino' AUD_INS_USER
from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO`
where grupos like '%GI%' and upsell = 'vips mp'
;



---insert GC

INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL(
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)  
select
cus_cust_id as USER_ID,
CAST(limite_final AS BIGINT) as GENERAL_LIMIT,
50 as WITHDRAW_LIMIT,
'MLB' SITE_ID,
0 PRIORITY,
1 IS_UPSELL,
'a351cb5e-9d24-4d61-b46f-c8ce2522cad3' CAMPAIGN_ID,
CASE WHEN grupos = 'GC' THEN TRUE ELSE FALSE END AS CAMPAIGN_CONTROL_GROUP,
 'gubelarmino' AS AUD_INS_USER
from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO`
where grupos like '%GC%' and upsell = 'vips mp'
;




---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'a351cb5e-9d24-4d61-b46f-c8ce2522cad3' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime '2025-08-05 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO` a
where grupos like '%GC%' and upsell = 'vips mp') A
;


--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'81f3e2b9-82e4-401a-b046-fc7018a07a07' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime '2025-08-05 00:00:00.000000'as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_VIP_20250805_GUBELARMINO` a
where grupos like '%GI%' and upsell = 'vips mp') A
;


