
--- ADECUACION RENTA ---
CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'CROSS', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'TEST COMBINADO', --5 Policy
'RENTA', --6 Policy Category
'BAU', --7 Policy_subcategory
'CAMBIO POLITICA RENTA OTROS', --8 Policy_description
'GESTION', --9 Campaign_group
'ADECUACION RENTA' --10 Campaign_group_desc
);

CALL`meli-bi-data.SBOX_CREDITS_SB.SP_INSERT_CAMPAIGN_INDEX` (
'MLB', --1 Sit_site_id
'CROSS', --2 Negocio
'TC FULL', --3 Product_desc
'UPSELL', -- 4 Campaign_type
'TEST COMBINADO', --5 Policy
'RENTA', --6 Policy Category
'BAU', --7 Policy_subcategory
'CAMBIO POLITICA RENTA OTROS', --8 Policy_description
'CONTROL', --9 Campaign_group
'ADECUACION RENTA' --10 Campaign_group_desc
);


-- check
select * from `meli-bi-data.SBOX_CREDITS_SB.CRD_VU_CAMPAIGN_INDEX` 
where sit_site_id = 'MLB'AND AUD_INS_USER = 'guilherme.belarmino@mercadopago.com.br' AND DATE(AUD_INS_DTTM) = CURRENT_DATE;

-- GESTION: 3e9dba8d-8e58-4187-8d46-ec893fe7a3e2
-- CONTROL: a28f1dad-2acb-4e2e-9d0a-a7c1758afb1e


-- GESTION
INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL (
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)
select
    cus_cust_id as USER_ID,
    CAST(limite_post_final AS BIGNUMERIC) AS GENERAL_LIMIT,
    50 as WITHDRAW_LIMIT,
    'MLB' AS SITE_ID,
    0 AS PRIORITY,
    1 AS IS_UPSELL,
    '3e9dba8d-8e58-4187-8d46-ec893fe7a3e2' AS CAMPAIGN_ID,
    false AS CAMPAIGN_CONTROL_GROUP,
    'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_TEST_ADECUACION_RENTA_202510_BASE_GI_GC_PECASTANHO` 
WHERE GRUPOS = 'GI'
-- Esta declaración agregó 30,924 filas a EOC_TC_C_UPSELL_DOWNSELL.
;


-- CONTROL
INSERT INTO meli-bi-data.SBOX_CREDITS_SB.EOC_TC_C_UPSELL_DOWNSELL (
USER_ID,
GENERAL_LIMIT,
WITHDRAW_LIMIT,
SITE_ID,
PRIORITY,
IS_UPSELL,
CAMPAIGN_ID,
CAMPAIGN_CONTROL_GROUP,
AUD_INS_USER
)
select
    cus_cust_id as USER_ID,
    CAST(limite_post_final AS BIGNUMERIC) AS GENERAL_LIMIT,
    50 as WITHDRAW_LIMIT,
    'MLB' AS SITE_ID,
    0 AS PRIORITY,
    1 AS IS_UPSELL,
    'a28f1dad-2acb-4e2e-9d0a-a7c1758afb1e' AS CAMPAIGN_ID,
    true AS CAMPAIGN_CONTROL_GROUP,
    'gubelarmino' AS AUD_INS_USER
from `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_TEST_ADECUACION_RENTA_202510_BASE_GI_GC_PECASTANHO` 
WHERE GRUPOS = 'GC'
-- Esta declaración agregó 3,433 filas a EOC_TC_C_UPSELL_DOWNSELL.
;


INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'3e9dba8d-8e58-4187-8d46-ec893fe7a3e2' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
CAST(LIMITE_POST_FINAL AS BIGNUMERIC) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(LIMITE_PRE AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
rating_bhv AS RATING_BHV_TC,
rating_upsell AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(LIMITE_PRE AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_TEST_ADECUACION_RENTA_202510_BASE_GI_GC_PECASTANHO`  a -- mudar
where GRUPOS = 'GI'
) A
;
-- Esta declaración agregó 30,924 filas a RBA_TC_CAMPAIGN_CARTERA.

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'a28f1dad-2acb-4e2e-9d0a-a7c1758afb1e' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP, -- mudar

null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
CAST(LIMITE_POST_FINAL AS BIGNUMERIC) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(LIMITE_PRE AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
rating_bhv AS RATING_BHV_TC,
rating_upsell AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(LIMITE_PRE AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_TEST_ADECUACION_RENTA_202510_BASE_GI_GC_PECASTANHO` a -- mudar
where GRUPOS = 'GC'
) A
;
-- Esta declaración agregó 3,433 filas a RBA_TC_CAMPAIGN_CARTERA.
