DECLARE DT_REF DATE;

SET DT_REF = '2025-12-26';

CREATE OR REPLACE TEMP TABLE TEMP_UNIVERSO AS

  SELECT 
    CUS_CUST_ID
  FROM `meli-bi-data.WHOWNER.BT_VU_CONSUMPTION` CNS
  WHERE CNS.VALID_TO_DT = '2099-12-31'
  AND CNS.SIT_SITE_ID = 'MLB'
  AND CNS.CRD_PROD_DEF_TYPE_SK = 3
  AND (CNS.ACTIVE_CREDITS_QTY + CNS.OVERDUE_CREDITS_QTY + CNS.ACTIVE_PROPOSALS_QTY) > 0

;

CREATE OR REPLACE TEMP TABLE TEMP_VU_CREDITS AS 

  SELECT
    CUS_CUST_ID,
    CRD_CREDIT_STATUS,
    TOTAL_AMT,
    CRD_CREDIT_STATUS_DT,
    CRD_PROP_ID,
    CRD_CREDIT_STATUS_DETAIL,
    MAX_OVERDUE_DAYS,
    OVERDUE_FLAG,
    LAST_PAID_DT,
    FIRST_PAID_DT,
    BALANCE_AMT,
    
  FROM `meli-bi-data.WHOWNER.BT_VU_CREDIT`
  WHERE 1=1
    AND SIT_SITE_ID = 'MLB'
    AND CRD_PROD_DEF_TYPE_SK = 3
    AND VALID_TO_DT >= DT_REF
    AND VALID_FROM_DT < DT_REF
;

CREATE OR REPLACE TEMP TABLE TEMP_CREDITS AS 

  SELECT 
    C.CUS_CUST_ID
    ,IFNULL(MAX(C.MAX_OVERDUE_DAYS),0) AS MAX_OVERDUE_DAYS_CREDITS_EVER_QTY
  FROM `meli-bi-data.WHOWNER.BT_VU_CREDIT` C
    WHERE 1=1
    AND C.VALID_TO_DT ='2099-12-31'
    AND C.CRD_PROD_DEF_TYPE_SK != 3
    AND C.CRD_CREDIT_STATUS IN ('CREDITED','FINISHED','ON_TIME','OVERDUE')
  GROUP BY ALL
;

CREATE OR REPLACE TEMP TABLE TEMP_VU_CONSUPTION AS 
  SELECT
    CUS_CUST_ID
    ,MAX(CASE WHEN CNS.LAST_BLOCKED_STATUS_DT > "1900-01-01" THEN TRUE ELSE FALSE END) AS CCARD_BLOCK_EVER_FLAG
  FROM `meli-bi-data.WHOWNER.BT_VU_CONSUMPTION` CNS
  WHERE VALID_TO_DT = "2099-12-31"
  AND SIT_SITE_ID = "MLB"
  GROUP BY CNS.CUS_CUST_ID

;


CREATE OR REPLACE TEMP TABLE TEMP_WANDA AS
  SELECT
    CUS_CUST_ID
    ,LAST_CCARD_PROPOSAL_STATUS -- K-TC-STATUS_DIF_ACCEPTED
    ,LAST_CCARD_PROP_STATUS
    ,PERSON_CREDIT_TRANSITORY_BLOCK_CCARD_FLAG -- R-ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT
    ,PERSON_ACTIVE_CCARD_CREDIT_FLAG -- R-ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT
    ,LIMIT_TC_AMT -- K-TC-LIMIT_ACTUAL_MENOR_IGUAL_500
    ,CCARD_BLOCK_EVER_FLAG -- R-MORA-EVER
    ,MAX_OVERDUE_DAYS_CREDITS_EVER_QTY -- R-MORA-EVER
    ,MAX_OVERDUE_DAYS_CCARD_EVER_QTY -- K-POWER-USER-MORA-EVER
    ,PERSON_EMPLOYEE_FLAG
    ,LAST_TC_UPSELL_DT
    ,LAST_TC_DOWNSELL_DT

    ,REAL_MIN_INST_TC_PERC
    ,REAL_USE_LEVEL_TC_VAL
    ,INTERNAL_RATING_BEHAVIOR_TC_TAG
    ,LAST_DIGIT_CUST_VAL
    ,MLB_EXTERNAL_RATING_DIFF_TAG
    ,MLB_EXTERNAL_RATING_TAG

    ,OVERLIMIT_TC_PERC
    ,TEORIC_RCI_CC_VAL
  FROM `WHOWNER.BT_MW_VARIABLES`
  WHERE 1=1
    AND SIT_SITE_ID = 'MLB'
;


CREATE OR REPLACE TEMP TABLE TEMP_PROSPECT AS 
  SELECT
    CUS_CUST_ID,
    VALID_FROM_DT,
    VALID_TO_DT,
    CATEGORY_LIFECYCLE_TAG,
    EMPLOYEE_FLAG,
    RISK_MANAGEMENT_TAG,
  FROM `WHOWNER.LK_VU_PROSPECT_UNIVERSE`
  WHERE 1=1
      AND SIT_SITE_ID = 'MLB'
      AND VALID_TO_DT >= DT_REF
      AND VALID_FROM_DT < DT_REF
  GROUP BY ALL
  ORDER BY 1
;

CREATE OR REPLACE TEMP TABLE TEMP_ASSUMED AS 

  SELECT
    CUS_CUST_ID
    ,VALID_TO_DT
    ,VALID_FROM_DT
    ,ASSUMED_INCOME_AMT
  FROM `WHOWNER.BT_VU_ASSUMED_INCOME` A
  WHERE 1=1
    AND SIT_SITE_ID = 'MLB'
      AND VALID_TO_DT >= DT_REF
      AND VALID_FROM_DT < DT_REF  
;

CREATE OR REPLACE TEMP TABLE TEMP_KILLERS AS

  SELECT
    *
  FROM (

    SELECT
      TEMP_WANDA.*,
      TEMP_PROSPECT.CATEGORY_LIFECYCLE_TAG,
      TEMP_PROSPECT.EMPLOYEE_FLAG,
      TEMP_PROSPECT.RISK_MANAGEMENT_TAG,
      TEMP_ASSUMED.ASSUMED_INCOME_AMT,
      CASE WHEN LAST_CCARD_PROPOSAL_STATUS <> 'ACCEPTED' THEN TRUE ELSE FALSE END AS K_STATUS_DIFF_ACCEPTED,
      CASE WHEN PERSON_CREDIT_TRANSITORY_BLOCK_CCARD_FLAG IS TRUE OR PERSON_ACTIVE_CCARD_CREDIT_FLAG IS TRUE THEN TRUE ELSE FALSE END AS R_ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT,
      CASE WHEN LIMIT_TC_AMT <= 500 THEN TRUE ELSE FALSE END AS K_TC_LIMIT_ACTUAL_MENOR_IGUAL_500,
      CASE WHEN CCARD_BLOCK_EVER_FLAG IS TRUE OR MAX_OVERDUE_DAYS_CREDITS_EVER_QTY > 5 THEN TRUE ELSE FALSE END AS R_MORA_EVER,
      CASE WHEN CATEGORY_LIFECYCLE_TAG = 'POWER USER' AND MAX_OVERDUE_DAYS_CREDITS_EVER_QTY < 10 AND MAX_OVERDUE_DAYS_CCARD_EVER_QTY < 10 THEN TRUE ELSE FALSE END AS K_POWER_USER_MORA_EVER,
      CASE WHEN PERSON_EMPLOYEE_FLAG IS TRUE THEN TRUE ELSE FALSE END AS K_NO_EMPLEADO_MELI,
      CASE WHEN LIMIT_TC_AMT > 20000 THEN TRUE ELSE FALSE END AS K_MLB_TC_MAX_LIMITE_ACTUAL_DW,
      CASE WHEN ASSUMED_INCOME_AMT IS NULL THEN TRUE ELSE FALSE END AS K_SIN_INGRESOS,
      CASE WHEN LAST_TC_UPSELL_DT >= DT_REF-90 THEN TRUE ELSE FALSE END AS K_90D_ULT_UPSELL_TC,
      CASE WHEN LAST_TC_DOWNSELL_DT >= DT_REF-90 THEN TRUE ELSE FALSE END AS K_90D_ULT_DOWNSELL_TC,

      (((LIMIT_TC_AMT*GREATEST(REAL_MIN_INST_TC_PERC, 1)*GREATEST(REAL_USE_LEVEL_TC_VAL, 0.8)*(1+OVERLIMIT_TC_PERC))+(TEORIC_RCI_CC_VAL*ASSUMED_INCOME_AMT))/ASSUMED_INCOME_AMT) AS RCI_CONJUNTA

    FROM TEMP_UNIVERSO -- TC ACEPTADA
    LEFT JOIN TEMP_WANDA      USING(CUS_CUST_ID)
    LEFT JOIN TEMP_PROSPECT   USING(CUS_CUST_ID)
    LEFT JOIN TEMP_ASSUMED    USING(CUS_CUST_ID)

    WHERE 1=1 
      AND RISK_MANAGEMENT_TAG = 'INDIVIDUAL' -- INDIVIDUALS
  )
;


SELECT
  count(1)
FROM TEMP_KILLERS
WHERE 1=1 -- 14.033.888
AND K_STATUS_DIFF_ACCEPTED IS FALSE -- 13945793
AND R_ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT IS TRUE -- 9214107
AND K_TC_LIMIT_ACTUAL_MENOR_IGUAL_500 IS FALSE -- 7300107
AND R_MORA_EVER IS TRUE -- 1887914
AND K_POWER_USER_MORA_EVER IS FALSE -- 1653201
AND K_NO_EMPLEADO_MELI IS FALSE -- 1648562
AND K_MLB_TC_MAX_LIMITE_ACTUAL_DW IS FALSE -- 1596989
AND K_SIN_INGRESOS IS FALSE -- 1596989
AND K_90D_ULT_UPSELL_TC IS FALSE -- 1270025
AND K_90D_ULT_DOWNSELL_TC IS FALSE -- 920640

;

CREATE OR REPLACE TEMP TABLE TEMP_POLICY AS 

SELECT
  *,
  CASE
    WHEN IFNULL(INTERNAL_RATING_BEHAVIOR_TC_TAG,'Z') NOT IN ('J') THEN 'a. rating bhv diff J'
    WHEN RCI_CONJUNTA IS NULL THEN 'b. exclusion universo 1'
    WHEN RCI_CONJUNTA <= 0.5 AND MLB_EXTERNAL_RATING_DIFF_TAG > 0 THEN 'c. exclusion universo 2'
    WHEN RCI_CONJUNTA <= 0.5 AND MLB_EXTERNAL_RATING_DIFF_TAG = -1 AND MLB_EXTERNAL_RATING_TAG IN ('A', 'B', 'C') THEN 'd. exclusion universo 3'
    WHEN RCI_CONJUNTA > 0.35 AND RCI_CONJUNTA <= 0.5 AND MLB_EXTERNAL_RATING_DIFF_TAG = 0 AND MLB_EXTERNAL_RATING_TAG IN ('A', 'B', 'C') THEN 'd. exclusion universo 4'
    WHEN RCI_CONJUNTA <= 0.35 AND MLB_EXTERNAL_RATING_DIFF_TAG = 0 THEN 'e. exclusion universo 5'
    ELSE 'z. calificable'
  END AS flag_policy
FROM TEMP_KILLERS
WHERE 1=1
  AND K_STATUS_DIFF_ACCEPTED IS FALSE
  AND R_ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT IS TRUE
  AND K_TC_LIMIT_ACTUAL_MENOR_IGUAL_500 IS FALSE
  AND R_MORA_EVER IS TRUE
  AND K_POWER_USER_MORA_EVER IS FALSE
  AND K_NO_EMPLEADO_MELI IS FALSE
  AND K_MLB_TC_MAX_LIMITE_ACTUAL_DW IS FALSE
  AND K_SIN_INGRESOS IS FALSE
  AND K_90D_ULT_UPSELL_TC IS FALSE
  AND K_90D_ULT_DOWNSELL_TC IS FALSE

;

CREATE OR REPLACE TABLE `SBOX_CREDITS_SB.RBA_TC_MLB_DOWNSELL_BAU_FUNNEL_SIMULACION_202512_GUBELARMINO` AS 
SELECT * FROM TEMP_KILLERS
;

CREATE OR REPLACE TABLE `SBOX_CREDITS_SB.RBA_TC_MLB_DOWNSELL_BAU_SIMULACION_202512_GUBELARMINO` AS 
SELECT * FROM TEMP_POLICY
