-- nao eh necessario mais realizar o insert


---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'03db0a8f-478d-498d-bd1f-a8d55bdf9a87' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime (current_date())as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251007_GI_GC_GUBELARMINO`  a
where grupos like '%GC%' and upsell = 'bau') A
;

-- Esta declaración agregó 8,201 filas a RBA_TC_CAMPAIGN_CARTERA.

--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'5ac338e8-747a-4c92-97f8-fcb523399b7c' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime(current_date())as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251007_GI_GC_GUBELARMINO`  a
where grupos like '%GI%' and upsell = 'bau') A
;

-- Esta declaración agregó 155,221 filas a RBA_TC_CAMPAIGN_CARTERA.


---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'a762d04d-bbfa-4980-88e6-54c10db327e9' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251007_GI_GC_GUBELARMINO`  a
where grupos like '%GC%' and upsell = 'vips mp') A
;

-- Esta declaración agregó 3,555 filas a RBA_TC_CAMPAIGN_CARTERA.

--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'bae5cc4a-c6bf-49e6-bf19-6d3aa751aa6f' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime(current_date()) as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251007_GI_GC_GUBELARMINO`  a
where grupos like '%GI%' and upsell = 'vips mp') A
;

-- Esta declaración agregó 67,034 filas a RBA_TC_CAMPAIGN_CARTERA.


---INSERT EN TABLA CARTERA
--GC

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

--
Select
'835c1996-68d5-4b70-b67b-9cdae62c493b' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP,
NULL as  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date()) as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC,
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(current_limit AS BIGINT) PREV_AMOUNT
FROM (
select * FROM  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251007_GI_GC_GUBELARMINO`  a
where grupos like '%GC%' and upsell = 'vips mktplace') A
;

-- Esta declaración agregó 4,477 filas a RBA_TC_CAMPAIGN_CARTERA.

--GI

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`  
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'1da83c48-b177-48fd-93fd-4bc4b353c1f9' as CAMPAIGN_ID,
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP,
null  PROP_ID, 
A.CUS_CUST_ID as CUS_CUST_ID, 
datetime(current_date()) as ACTIONABLE_DTTM, 
CAST(limite_final AS BIGINT) as AMOUNT, 
NULL RATING,
NULL RATING_CH_TC, --- 
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, -- 
NULL RATING_CH_CC, -- 
NULL MODELO_BHV_CC, -- 
NULL RATING_BHV_CC, -- 
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --? 
NULL PORC_USO_TC,
NULL LIMITE_TC,
NULL PORC_PAGO_MIN,
--CAST(A.NIVEL_USO_TC_UPS AS BIGINT) PORC_USO_TC, --
--CAST(A.LIMITE_ACTUAL AS BIGINT) LIMITE_TC, -- 
--CAST(A.PAGO_MIN_TC_UPS AS BIGINT) PORC_PAGO_MIN ,  -- 
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, -- 
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, --- 
current_datetime() as AUD_INS_DTTM,
A.rating_bhv_tc AS RATING_BHV_TC, --
A.rating_upsell_tc AS RATING_UPSELL_TC, 
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(A.current_limit AS BIGINT)  PREV_AMOUNT --

FROM (
select * from  `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_BAU_20251007_GI_GC_GUBELARMINO`  a
where grupos like '%GI%' and upsell = 'vips mktplace') A
;



INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'ed0fb2fd-0a4b-4db1-84c9-562724346d25' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
GENERAL_LIMIT as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
INTERNAL_RATING_BEHAVIOR_TC AS RATING_BHV_TC,
INTERNAL_RATING_UPSELL_TC AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_ANALITICA_20251009_GUBELARMINO` a -- mudar
where FLAG_CONTROL_GROUP is false
) A
;
-- Esta declaración agregó 69,686 filas a RBA_TC_CAMPAIGN_CARTERA.


INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'eaea3192-652a-4a2d-bc43-715a8e915fa3' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
GENERAL_LIMIT as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
INTERNAL_RATING_BEHAVIOR_TC AS RATING_BHV_TC,
INTERNAL_RATING_UPSELL_TC AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(WANDA__CURRENT_LIMIT_CCARD AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_JOURNEY_LIMITE_ANALITICA_20251009_GUBELARMINO` a -- mudar
where FLAG_CONTROL_GROUP is true
) A
;
-- Esta declaración agregó 7,726 filas a RBA_TC_CAMPAIGN_CARTERA.




INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'3e9dba8d-8e58-4187-8d46-ec893fe7a3e2' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'IMPACTO_1' as CAMPAIGN_GROUP, -- mudar
null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
CAST(LIMITE_POST_FINAL AS BIGNUMERIC) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(LIMITE_PRE AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
rating_bhv AS RATING_BHV_TC,
rating_upsell AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(LIMITE_PRE AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_TEST_ADECUACION_RENTA_202510_BASE_GI_GC_PECASTANHO`  a -- mudar
where GRUPOS = 'GI'
) A
;
-- Esta declaración agregó 30,924 filas a RBA_TC_CAMPAIGN_CARTERA.

INSERT INTO `SBOX_CREDITS_SB.RBA_TC_CAMPAIGN_CARTERA`
(
CAMPAIGN_ID,
SIT_SITE_ID,
PRODUCT,
PRODUCT_ID,
ACTIONABLE_NAME,
CAMPAIGN_GROUP,
PROP_ID,
CUS_CUST_ID,
ACTIONABLE_DTTM,
AMOUNT,
RATING,
RATING_CH_TC,
RATING_CH_TC_SCR,
MODELO_CH_CC,
RATING_CH_CC,
MODELO_BHV_CC,
RATING_BHV_CC,
RATING_ADP_CC,
PORC_USO_CC,
LINEA_CC,
PLAZO_CC,
PORC_USO_TC,
LIMITE_TC,
PORC_PAGO_MIN,
MONTO_DISPO_CC,
PRESUMED_INCOME,
FLAG_MERCHANT,
RCI_CONCEPTUAL,
RCI_REAL,
SEGMENT_SELLER,
LYL_LEVEL_NUMER,
NUMERO_ENCENDIDO,
FLAG_MP,
FLAG_SCR,
LIMITE_TC_INFERIDO,
FLAG_IN_WHOW,
AUD_INS_DTTM,
RATING_BHV_TC,
RATING_UPSELL_TC,
PORC_USO_TC_REAL,
PORC_PAGO_MIN_REAL,
PORC_USO_CC_REAL,
PLAZO_PROMEDIO_REAL,
PREV_AMOUNT
)

-----
Select
'a28f1dad-2acb-4e2e-9d0a-a7c1758afb1e' as CAMPAIGN_ID, -- mudar
'MLB' as SIT_SITE_ID,
'TC' as PRODUCT,
1 as PRODUCT_ID,
'CCARD_UPSELL' as ACTIONABLE_NAME,
'CONTROL_1' as CAMPAIGN_GROUP, -- mudar

null PROP_ID,
A.CUS_CUST_ID as CUS_CUST_ID,
datetime(current_date())as ACTIONABLE_DTTM,
CAST(LIMITE_POST_FINAL AS BIGNUMERIC) as AMOUNT,
NULL RATING,
NULL RATING_CH_TC, ---
NULL RATING_CH_TC_SCR, --
NULL MODELO_CH_CC, --
NULL RATING_CH_CC, --
NULL MODELO_BHV_CC, --
NULL RATING_BHV_CC, --
NULL RATING_ADP_CC, --
NULL PORC_USO_CC, --
NULL LINEA_CC, --
NULL PLAZO_CC, --
CAST(NIVEL_USO_TC_UPS AS NUMERIC) PORC_USO_TC, --
CAST(LIMITE_PRE AS NUMERIC) LIMITE_TC, --
CAST(PAGO_MIN_TC_UPS AS NUMERIC) PORC_PAGO_MIN , --
NULL monto_dispo_cc , --
NULL PRESUMED_INCOME , --
NULL FLAG_MERCHANT, --
NULL RCI_CONCEPTUAL, --
NULL RCI_REAL, --
NULL SEGMENT_SELLER,
NULL LYL_LEVEL_NUMER,
NULL NUMERO_ENCENDIDO, --
NULL FLAG_MP,
NULL FLAG_SCR,
NULL LIMITE_TC_INFERIDO,
NULL FLAG_IN_WHOW, ---
current_datetime() as AUD_INS_DTTM,
rating_bhv AS RATING_BHV_TC,
rating_upsell AS RATING_UPSELL_TC,
NULL PORC_USO_TC_REAL,
NULL PORC_PAGO_MIN_REAL,
NULL PORC_USO_CC_REAL,
NULL PLAZO_PROMEDIO_REAL,
CAST(LIMITE_PRE AS NUMERIC) PREV_AMOUNT
FROM (
select * FROM `meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_UPSELL_TEST_ADECUACION_RENTA_202510_BASE_GI_GC_PECASTANHO` a -- mudar
where GRUPOS = 'GC'
) A
;
-- Esta declaración agregó 3,433 filas a RBA_TC_CAMPAIGN_CARTERA.
