
declare table_name_dwtc string;
declare table_name_dwtc_base string;
declare table_name_dwtc_impacto string;
declare dt_ref date;

set table_name_dwtc = concat('meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_DOWNSELL_BAU_ACTIVOS_HIST_', format_date('%Y%m%d', current_date()), '_GUBELARMINO');
set table_name_dwtc_base = concat('meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_DOWNSELL_BAU_ACTIVOS_BASE_', format_date('%Y%m%d', current_date()), '_GUBELARMINO');
set table_name_dwtc_impacto = concat('meli-bi-data.SBOX_CREDITS_SB.RBA_TC_MLB_DOWNSELL_BAU_ACTIVOS_IMPACTABLES_', format_date('%Y%m%d', current_date()), '_GUBELARMINO');
set dt_ref = current_date();

execute immediate '''
create or replace table ''' || table_name_dwtc || '''
as

WITH TEMP_UNIVERSO AS (

  SELECT 
    CUS_CUST_ID
  FROM `meli-bi-data.WHOWNER.BT_VU_CONSUMPTION` CNS
  WHERE CNS.VALID_TO_DT = '2099-12-31'
  AND CNS.SIT_SITE_ID = 'MLB'
  AND CNS.CRD_PROD_DEF_TYPE_SK = 3
  AND (CNS.ACTIVE_CREDITS_QTY + CNS.OVERDUE_CREDITS_QTY + CNS.ACTIVE_PROPOSALS_QTY) > 0

)
, TEMP_WANDA AS (
  SELECT
    CUS_CUST_ID
    ,LAST_CCARD_PROPOSAL_STATUS -- K-TC-STATUS_DIF_ACCEPTED
    ,LAST_CCARD_PROP_STATUS
    ,PERSON_CREDIT_TRANSITORY_BLOCK_CCARD_FLAG -- R-ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT
    ,PERSON_ACTIVE_CCARD_CREDIT_FLAG -- R-ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT
    ,LIMIT_TC_AMT -- K-TC-LIMIT_ACTUAL_MENOR_IGUAL_500
    ,CCARD_BLOCK_EVER_FLAG -- R-MORA-EVER
    ,MAX_OVERDUE_DAYS_CREDITS_EVER_QTY -- R-MORA-EVER
    ,MAX_OVERDUE_DAYS_CCARD_EVER_QTY -- K-POWER-USER-MORA-EVER
    ,PERSON_EMPLOYEE_FLAG
    ,LAST_TC_UPSELL_DT
    ,LAST_TC_DOWNSELL_DT

    ,REAL_MIN_INST_TC_PERC
    ,REAL_USE_LEVEL_TC_VAL
    ,CCARD_USAGE_PCT
    ,INTERNAL_RATING_BEHAVIOR_TC_TAG
    ,LAST_DIGIT_CUST_VAL
    ,MLB_EXTERNAL_RATING_DIFF_TAG
    ,MLB_EXTERNAL_RATING_TAG

    ,OVERLIMIT_TC_PERC
    ,TEORIC_RCI_CC_VAL
  FROM `WHOWNER.BT_MW_VARIABLES`
  WHERE 1=1
    AND SIT_SITE_ID = 'MLB'
)

, TEMP_PROSPECT AS (
  SELECT
    CUS_CUST_ID,
    VALID_FROM_DT,
    VALID_TO_DT,
    CATEGORY_LIFECYCLE_TAG,
    EMPLOYEE_FLAG,
    RISK_MANAGEMENT_TAG,
  FROM `WHOWNER.LK_VU_PROSPECT_UNIVERSE`
  WHERE 1=1
      AND SIT_SITE_ID = 'MLB'
      AND VALID_TO_DT = '2099-12-31'
  GROUP BY ALL
  ORDER BY 1
)

, TEMP_ASSUMED AS ( 

  SELECT
    CUS_CUST_ID
    ,VALID_TO_DT
    ,VALID_FROM_DT
    ,ASSUMED_INCOME_AMT
  FROM `WHOWNER.BT_VU_ASSUMED_INCOME` A
  WHERE 1=1
    AND SIT_SITE_ID = 'MLB'
    AND VALID_TO_DT = '2099-12-31'

)

, TEMP_KILLERS AS ( 
  SELECT
    *
  FROM (

    SELECT
      TEMP_WANDA.*,
      TEMP_PROSPECT.CATEGORY_LIFECYCLE_TAG,
      TEMP_PROSPECT.EMPLOYEE_FLAG,
      TEMP_PROSPECT.RISK_MANAGEMENT_TAG,
      TEMP_ASSUMED.ASSUMED_INCOME_AMT,
      CASE WHEN LAST_CCARD_PROPOSAL_STATUS <> 'ACCEPTED' THEN TRUE ELSE FALSE END AS K_STATUS_DIFF_ACCEPTED,
      CASE WHEN PERSON_CREDIT_TRANSITORY_BLOCK_CCARD_FLAG IS TRUE OR PERSON_ACTIVE_CCARD_CREDIT_FLAG IS TRUE THEN TRUE ELSE FALSE END AS R_ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT,
      CASE WHEN LIMIT_TC_AMT <= 500 THEN TRUE ELSE FALSE END AS K_TC_LIMIT_ACTUAL_MENOR_IGUAL_500,
      CASE WHEN CCARD_BLOCK_EVER_FLAG IS TRUE OR MAX_OVERDUE_DAYS_CREDITS_EVER_QTY > 5 THEN TRUE ELSE FALSE END AS R_MORA_EVER,
      CASE WHEN CATEGORY_LIFECYCLE_TAG = 'POWER USER' AND MAX_OVERDUE_DAYS_CREDITS_EVER_QTY < 10 AND MAX_OVERDUE_DAYS_CCARD_EVER_QTY < 10 THEN TRUE ELSE FALSE END AS K_POWER_USER_MORA_EVER,
      CASE WHEN PERSON_EMPLOYEE_FLAG IS TRUE THEN TRUE ELSE FALSE END AS K_NO_EMPLEADO_MELI,
      CASE WHEN LIMIT_TC_AMT > 20000 THEN TRUE ELSE FALSE END AS K_MLB_TC_MAX_LIMITE_ACTUAL_DW,
      CASE WHEN ASSUMED_INCOME_AMT IS NULL THEN TRUE ELSE FALSE END AS K_SIN_INGRESOS,
      CASE WHEN LAST_TC_UPSELL_DT >= current_date()-90 THEN TRUE ELSE FALSE END AS K_90D_ULT_UPSELL_TC,
      CASE WHEN LAST_TC_DOWNSELL_DT >= current_date()-90 THEN TRUE ELSE FALSE END AS K_90D_ULT_DOWNSELL_TC,

      (((LIMIT_TC_AMT*GREATEST(REAL_MIN_INST_TC_PERC, 1)*GREATEST(REAL_USE_LEVEL_TC_VAL, 0.8)*(1+OVERLIMIT_TC_PERC))+(TEORIC_RCI_CC_VAL*ASSUMED_INCOME_AMT))/ASSUMED_INCOME_AMT) AS RCI_CONJUNTA

    FROM TEMP_UNIVERSO -- TC ACEPTADA
    LEFT JOIN TEMP_WANDA      USING(CUS_CUST_ID)
    LEFT JOIN TEMP_PROSPECT   USING(CUS_CUST_ID)
    LEFT JOIN TEMP_ASSUMED    USING(CUS_CUST_ID)

    WHERE 1=1 
      AND RISK_MANAGEMENT_TAG = 'INDIVIDUAL' -- INDIVIDUALS
  )
)

SELECT * FROM TEMP_KILLERS

;

''';

execute immediate '''
select
  count(1)
from ''' || table_name_dwtc || '''
;
''';

execute immediate '''
select
   cus_cust_id
  ,count(1) as cant
from ''' || table_name_dwtc || '''
group by all
having cant>1
;
''';

execute immediate '''
create or replace table ''' || table_name_dwtc_base || '''
as

WITH TEMP_POLICY AS (

SELECT
  *,
  CASE
    WHEN IFNULL(INTERNAL_RATING_BEHAVIOR_TC_TAG,'Z') NOT IN ('J') THEN 'a. rating bhv diff J'
    WHEN RCI_CONJUNTA IS NULL THEN 'b. exclusion universo 1'
    WHEN RCI_CONJUNTA <= 0.5 AND MLB_EXTERNAL_RATING_DIFF_TAG > 0 THEN 'c. exclusion universo 2'
    WHEN RCI_CONJUNTA <= 0.5 AND MLB_EXTERNAL_RATING_DIFF_TAG = -1 AND MLB_EXTERNAL_RATING_TAG IN ('A', 'B', 'C') THEN 'd. exclusion universo 3'
    WHEN RCI_CONJUNTA > 0.35 AND RCI_CONJUNTA <= 0.5 AND MLB_EXTERNAL_RATING_DIFF_TAG = 0 AND MLB_EXTERNAL_RATING_TAG IN ('A', 'B', 'C') THEN 'd. exclusion universo 4'
    WHEN RCI_CONJUNTA <= 0.35 AND MLB_EXTERNAL_RATING_DIFF_TAG = 0 THEN 'e. exclusion universo 5'
    WHEN PERSON_CREDIT_TRANSITORY_BLOCK_CCARD_FLAG IS TRUE then 'f. overdue'
    ELSE 'z. calificable'
  END AS flag_policy
FROM ''' || table_name_dwtc || '''
WHERE 1=1
  AND K_STATUS_DIFF_ACCEPTED IS FALSE
  AND R_ACTIVE_OR_BLOCK_TRANSITORIO_ACCOUNT IS TRUE
  AND K_TC_LIMIT_ACTUAL_MENOR_IGUAL_500 IS FALSE
  AND R_MORA_EVER IS TRUE
  AND K_POWER_USER_MORA_EVER IS FALSE
  AND K_NO_EMPLEADO_MELI IS FALSE
  AND K_MLB_TC_MAX_LIMITE_ACTUAL_DW IS FALSE
  AND K_SIN_INGRESOS IS FALSE
  AND K_90D_ULT_UPSELL_TC IS FALSE
  AND K_90D_ULT_DOWNSELL_TC IS FALSE
)

select * from TEMP_POLICY

;
''';


execute immediate '''
create or replace table ''' || table_name_dwtc_impacto || '''
as

WITH TEMP_LIMITES AS (
  SELECT
    *,
    CASE WHEN GENERAL_LIMIT >= LIMIT_TC_AMT OR ABS(GENERAL_LIMIT-LIMIT_TC_AMT) <= 50 THEN 1 ELSE 0 END AS K_DOWNSELL_INSUFICIENTE,
    ROUND(GENERAL_LIMIT/LIMIT_TC_AMT,1) AS MULTIPLICADOR_FINAL
  FROM (
    SELECT
      *except(general_limit),
      CASE WHEN general_limit < 500 THEN 500 ELSE general_limit END AS GENERAL_LIMIT
    FROM
    (
      SELECT
        *,
        CASE 
          WHEN SUBSTR(CAST(cus_cust_id AS STRING), 2, 1) <= '4' THEN 0.4*LIMIT_TC_AMT
          WHEN SUBSTR(CAST(cus_cust_id AS STRING), 2, 1) >  '4' THEN 0.6*LIMIT_TC_AMT
          ELSE -1
        END AS general_limit
      FROM ''' || table_name_dwtc_base || '''
      where 1=1
        and flag_policy = 'z. calificable'
    )
  )
)

SELECT 
  *,
  CASE 
      WHEN RIGHT(CAST(cus_cust_id AS STRING), 1) = '0' THEN true 
      WHEN RIGHT(CAST(cus_cust_id AS STRING), 1) > '0' THEN false
  END AS CAMPAIGN_CONTROL_GROUP
FROM TEMP_LIMITES
WHERE K_DOWNSELL_INSUFICIENTE = 0

;
''';

execute immediate '''
select
   flag_policy
  ,count(1) as cant
from ''' || table_name_dwtc_base || '''
group by all
order by 1 asc
;
''';

execute immediate '''
select
  "BAU" AS TIPO_DOWNSELL,
  CAMPAIGN_CONTROL_GROUP,
  COUNT(1) AS CANT,
  ROUND(SUM(GENERAL_LIMIT-LIMIT_TC_AMT),2) AS EXPOSICION_REDUZIDA,
  ROUND(AVG(GENERAL_LIMIT),2) AS LIMITE_PROMEDIO_POST,
  ROUND(AVG(GENERAL_LIMIT/LIMIT_TC_AMT),1) AS MULTIPLICADOR_PROMEDIO,
  AVG(CCARD_USAGE_PCT) AS IU_PROMEDIO,
from ''' || table_name_dwtc_impacto || '''
group by all
order by 1 asc
;
''';