

/****************************************************
         BLACKLISTEO DE USUARIOS
****************************************************/

INSERT INTO SBOX_CREDITSSHARED.CRD_PARAM_BLACKLIST_CREDITS 
(USER_RELACIONADO,
USER_ORIGINAL,
CRUCE_DEV_ML,
CRUCE_DEV_THM,
CRUCE_DOC,
CRUCE_TC,
COMENTARIO,
INSERT_DATE) 
SELECT
A.CUST_ID AS USER_RELACIONADO,
A.CUST_ID AS USER_ORIGINAL,
0 AS CRUCE_DEV_ML,
0 AS CRUCE_DEV_THM,
1 AS CRUCE_DOC,
0 AS CRUCE_TC,
'BASE COMPARTIDA POR TEAM FRAUDE 20250407' AS COMENTARIO,
CURRENT_DATE AS INSERT_DATE
FROM SBOX_CREDITS_SB.RBA_CC_MLB_FRAUDE_GABCERQUEIRA A
WHERE 1=1
;

--Check
SELECT 
USER_RELACIONADO 
FROM SBOX_CREDITSSHARED.CRD_PARAM_BLACKLIST_CREDITS 
WHERE 1=1
AND COMENTARIO = 'BASE COMPARTIDA POR TEAM FRAUDE 20250407'
;
